### ISSUE TITLE
Example for word replacements

### ISSUE THREAD

**Issue by jvillalobos** [mdn/webextensions-examples#103]
A common type of add-on we see being created, mostly for entertainment purposes, are add-ons that make word/phrase replacements, like [XKCD Substitutions](https://addons.mozilla.org/addon/xkcd-substitutions/). This would also make a good example for beginners that could be reused to create real add-ons.

Discussing it with my team, we came up with the idea of a word -> emoji substitution add-on. It could use a simple mapping (from http://emojipedia.org/ or similar) to replace a bunch of common words for emojis.

One minor caveat is that we should make sure the replacement script has decent performance, since it could end up being replicated multiple times.

**Comment by atsay** [comment]
The plan would be to turn this example into a "make your first add-on" tutorial that we can provide as an activity on the mozilla.org/contribute page and Campus Clubs.

**Comment by aterranova-bv** [comment]
This sounds awesome, I'm on it! 🎃

**Comment by jvillalobos** [comment]
🏆

**Comment by wbamberg** [comment]
Fixed: https://github.com/mdn/webextensions-examples/pull/110.
