### ISSUE TITLE
Get rid of innerHTML

### ISSUE THREAD

**Issue by wagnerand** [mdn/webextensions-examples#115]
Reviewers discourage the use of `innerHTML` for security and performance reasons. Let's live up to our own best practices. :)

There are currently only two occurrences:
```
history-deleter/history.js
17:  document.getElementById('history').innerHTML = `No history for ${hostname}.`;

navigation-stats/popup.js
17:  listEl.innerHTML = "";
```

**Comment by Hrily** [comment]
I would like to work upon it...
Is it okay to use DOM methods?

**Comment by wbamberg** [comment]
> I would like to work upon it...

Great!

> Is it okay to use DOM methods?

Yes!

**Comment by Hrily** [comment]
Can you tell me what does the ${} operator do?
I'm not able to get it.

**Comment by wbamberg** [comment]
It's for interpolation in template literals: "Template literals are string literals allowing embedded expressions."

-> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals.

**Comment by Hrily** [comment]
So, \`\` no different than a "" string?

**Comment by wbamberg** [comment]
No, it is different.

`` is used to create a template literal, which enables you to do string interpolation:

```
var sub = "World";
var greet1 = `Hello ${sub}` // -> "Hello World"
var greet2 = "Hello ${sub}" // -> "Hello ${sub}"
```

**Comment by Hrily** [comment]
Okay, I didn't know about them...

**Comment by Hrily** [comment]
I have made a PR. #116 
Can you review it?

**Comment by wbamberg** [comment]
Merged https://github.com/mdn/webextensions-examples/pull/116. Thanks @Hrily !

**Comment by Hrily** [comment]
Welcome :) 
Even if it is a small modification, I'm feeling proud as my first Open Source contribution is to the MDN :D
