### ISSUE TITLE
Example using indexeddb

### ISSUE THREAD

**Issue by andymckay** [mdn/webextensions-examples#119]
Maybe an example using indexeddb would be nice? Could maybe integrate with an API we currently don't have an example with. Doesn't need to be complicated, just shows that you can use it in a background page.

https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API

**Comment by Pheil** [comment]
When testing this code with FF 52.0a2 (2017-01-20) I get the following error.  Is access to IndexedDB supported yet?

"IndexedDB request denied"

**Comment by wbamberg** [comment]
@Pheil , I think IndexedDB access from WebExtensions should work just fine in the current Firefox. I haven't tried the add-on associated with this particular issue, but I did try this one: https://github.com/mdn/webextensions-examples/pull/171 (also not merged yet) and it worked fine for me.

**Comment by biphobe** [comment]
@wbamberg Didn't this issue become obsolete after merging #224?

**Comment by wbamberg** [comment]
Yes, looks like it :). Thanks!
