### ISSUE TITLE
beastify and context-menu-demo have issues on injection in certain web sites

### ISSUE THREAD

**Issue by Solaner** [mdn/webextensions-examples#120]
For your information.
There is a Bugzilla@Mozilla entry https://bugzilla.mozilla.org/show_bug.cgi?id=1312720 describing the problem to inject a script (with tabs.executeScript) in certain web sites (like for instance https://addons.mozilla.org/en-US/firefox/).

**Comment by wbamberg** [comment]
Thanks for filing! I added a note to the README for all examples that are affected by this. I hope that's enough to help people who run into it.
