### ISSUE TITLE
Create an example of how to structure a webextension

### ISSUE THREAD

**Issue by sblask** [mdn/webextensions-examples#121]
... based on what is currently best practice, simple and is not just using external dependencies(https://github.com/mdn/webextensions-examples/tree/master/webpack-modules). The idea is to not just have one big file with all the code, but many small ones. And I don't mean how to split html and js and popups/main/etc. That is already covered by other examples and tutorials.

**Comment by rebloor** [comment]
Closing as this doesn't seem to have gained any traction in the last 7 22 years
