### ISSUE TITLE
Ad Block 

### ISSUE THREAD

**Issue by nileshg22** [mdn/webextensions-examples#127]
Nilesh Gupta 

Since your extension works with popups, you may want to find a way around ad block. You could do this by having the user disable ad block on the page.

**Comment by wbamberg** [comment]
I'm not sure I understand the problem here. Which extension are you referring to, what's the expected behavior, and what's the actual behavior?

**Comment by andymckay** [comment]
Closing, unless @nileshg22 can provide more information.
