### ISSUE TITLE
Extensions are not being loaded on domain https://addons.mozilla.org/

### ISSUE THREAD

**Issue by icl7126** [mdn/webextensions-examples#136]
For example this one:
https://github.com/mdn/webextensions-examples/tree/master/emoji-substitution

Is not gonna be loaded on this domain:
https://addons.mozilla.org/

even when it's setup as: `"matches": ["<all_urls>"]`

EDIT:
this affects current beta version 50.0b11 only. Release 49.02 is not affected.

**Comment by kumar303** [comment]
This is by design. You can't manipulate this domain since Firefox grants it
special powers to install extensions. You can use pretty much any other
domain though.

**Comment by icl7126** [comment]
Good to know,  thanks.
Just to be sure, this applies for temporary loaded extension only, right?
Normal extensions signed by Mozilla will work. Right?
