### ISSUE TITLE
webpack-modules example is confusing, also no link to Browserify

### ISSUE THREAD

**Issue by Leif-W** [mdn/webextensions-examples#150]
The broad concept, use an npm based module inside an add-on, I understand the need for this.  I'd like to use Leaflet (and a few modules) to create an interactive map used to configure geographical regions (click-add and click-drag points to create one or more polygons) which my add-on would then do something with that data (polygon co-ordinates), etc.  That is a bit beyond the scope and simplicity of an example, but I understand the benefit of the approach.  I came to this example to shed some light on how that larger goal may be achieved.

But I am not familiar with webpack, or Browserify, or left-pad.  I don't get a clear sense of what they are doing, what is going on, and why the code is the way it is, or the ways the example code might be varied to achieve the same thing, or if I want to change behaviors (different locations, different parts of browser i.e. context menu vs browser action vs page action vs popup vs options_ui), or if it must always look exactly like this...  While I understand how to learn these kinds of things (eventually) through reading the upstream docs, StackOverflow searches and trial and error, it'd be handy to have a clearer explanation, maybe code comments for the fairly cryptic code.

I don't know precisely WHAT webpack and Browserify do exactly, how they differ, strengths and weaknesses, pros and cons, etc.  So I figured I'd try and read about them.  The README.md links to [webpack](http://webpack.js.org/) URL, which is very convenient and helpful to the learning process, to quickly load the page.  But there's no link to [Browserify](http://browserify.org/), which interrupts my flow and now I have to go search for it.

At the very least, linking that would be handy.  And perhaps to any other popular or well-built tools of the same nature.

As for my budding understanding, I think that the software npm package we wish to include has to have been written to export all the objects, functions and variables that we wish to use, and then these packers analyze our code to see specifically which modules we "require()", and which exported items we actually used, then "minifies" this into a monolithic ".js" file.  Questions arise about how to handle the scenario where, say, background and options_ui scripts both need access to the same code.  Rather than copy an entire massive library into both scripts, can we split off any commonly used things into a common script that each part of our add-on can load?  Effectively two copies would run in memory, but at least there wouldn't be two copies in the .xpi making distribution size larger with redundant code.  A more "meaty" example might be helpful here, as well as plainly stated documentation and code comments, aimed at someone who maybe has never had any experience with any of this.

**Comment by sneakypete81** [comment]
Another way to use npm to manage your dependencies is to symlink into node_modules. This bypasses the complexities of Webpack/Browserify, you'll just need to understand which files in your dependencies need to be included in your addon. Usually the `dist` subdirectory is the place to look.

For example, to install JQuery:

* Run `npm init` and answer the questions. This will create an example `package.json`.
* Install JQuery with `npm install jquery --save`. This will update your `package.json` with the latest version.
* Create symlinks to the dependencies from a folder inside your addon. Assuming your addon code is in the `addon` subdirectory:
```
mkdir addon/vendor
cd addon/vendor
ln -s ../../node_modules/jquery/dist/jquery.js
```

And, as usual, any devDependencies (eg. web-ext) can be installed with `npm install web-ext --save-dev`.

I'm not sure that this warrants an example of its own, but I've found it to be a useful way to manage external dependencies.

**Comment by Leif-W** [comment]
Appreciate the alternative.  I'm still wrapping my head around Node packages in general.  I've got web-ext installed globally with -g.  Would I uninstall that and reinstall locally into each and every add-on (assuming I make more than one)?  Or do that once, find out what folder it lives in, and symlink back to the global position?  (Although that seems to be fighting against the entire design concept of Node package management.)

FYI for windows translation of above symlink code, for anyone else reading:

```
md addon\vendor
cd addon\vendor
mklink jquery.js ../../node_modules/jquery/dist/jquery.js
```

Still not sure what technique I will use.  Probably try a few things.

**Comment by wbamberg** [comment]
I've added a link to Browserify.

I don't think these examples are the place to document these other tools. They have excellent docs of their own, and you'll need to read them anyway to be able to use them effectively.
