### ISSUE TITLE
favourite colours - red, white and blue!  ;-)  re-American-ified

### ISSUE THREAD

**Issue by Leif-W** [mdn/webextensions-examples#151]
Well, I am American, so I re-American-ified this example offline, so that I don't have to type spurious 'u's as I play with it to modify and learn.  The Brits lost the war a long time ago.  They and their former colonies better get used to speaking American English!  We've been taking over the world for more than two centuries now!

P.S. This is not so much an issue as a facetious commentary meant in good humor.  Thank you for the example, it helped me learn to save options into storage in "options_ui" and pick up changes in "background" with a storage on change event listener.

**Comment by wbamberg** [comment]
Thanks for the feedback. Some contributors to this repo are from the UK and are welcome to use their local spelling in the examples they contribute.

**Comment by Leif-W** [comment]
Absolutely, thanks to all contributors, no matter which planet you're from!  My joke was to adopt the persona of the stereotypical American, who could probably do with a bit of de-American-ification in that regard.

**Comment by kumar303** [comment]
You could have called it "international English" for a more biting wit 🔥
