### ISSUE TITLE
open-my-page-button/background.js uses chrome.extension.getURL

### ISSUE THREAD

**Issue by Leif-W** [mdn/webextensions-examples#152]
File: webextensions-examples/open-my-page-button/background.js
Function: openMyPage
Problem: Uses chrome.extension.getURL, which creates 2 issues.

First, I think the proper name in the API is [browser.extension.getURL](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extension/getURL).  However, this could also be done with [browser.runtime.getURL](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getURL).

Second, this function call may be superfluous, as browser.tabs.create will accept a string for the 'url' parameter, in which case it will (presumably and implicitly) call a similar function internally, and generate a moz-extension://GUID/relative/path.html .

```
	browser.tabs.create( {
		'url': 'relative/path.html'
	} );
```

From [browser.tabs.create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) :

> url  Optional
>     string. The URL to navigate the tab to initially. Fully-qualified URLs must include a scheme (i.e. 'http://www.google.com', not 'www.google.com'). Relative URLs will be relative to the current page within the extension. Defaults to the New Tab Page.

Not sure what the "current page within the extension" refers to.  This documentation is ambiguous.  Can the relative position change?  Most of these type of functions seem to be anchored off the location of the manifest.json.  Is this method unreliable?  Should one of the getURL methods above be used?  The getURL methods seem to be the same interface shared between two objects in the API.

**Comment by wbamberg** [comment]
Yes, you're right, I think getURL is not needed.

On relative URLs, I think that:

* in Chrome, relative URLs are interpreted relative to the manifest.json.

* in Firefox, they are interpreted relative to the location of the document hosting the JS that's making the `browser.tabs.create()` call. By default, if the code is running in a background page, and you don't specify a background page, then the background page's path is the add-on's root (that is, the same directory as manifest.json). But if you define your own background page location, or are making the call from a popup, say, then the URL is interpreted relative to the popup or background page location.

To work cross-browser, you can specify the path as an absolute URL, starting at the add-on's root, like `"/path/to/my-page.html"`.

So for instance, consider:

    my-addon/
        manifest.json
        my-page/
            my-page.html
        my-popup/
            my-popup.html
            my-popup.js

Suppose `my-popup.html` loads `my-popup.js`, and `my-popup.js` wants to open `my-page.html`. In Firefox, both of these will work:

    "../my-page/my-page.html"
    "/my-page/my-page.html"

In Chrome, both of these will work:

    "my-page/my-page.html"
    "/my-page/my-page.html"

**Comment by Leif-W** [comment]
Thanks for this clarification!  The absolute URL will always start with "root" (/) at "manifest.json", cross browser.  And reliance upon any mechanism that will take a string and convert it to a fully qualified URL without having to explicitly call a function, makes the code cleaner in the sense that, say, if "browser." ever changes to "firefox." as it did from "chrome.", or one of the redundant ".getURL" functions is removed, the one you happened to pick in a coin toss decision.

**Comment by wbamberg** [comment]
> Also, perhaps the documentation could mention the absolute path starting with manifest.json:

Yes, this is done: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create#Parameters. There are definitely other places where the same advice applies, but I think it's OK to duplicate it.

Thanks for raising the issue. This is definitely a non-obvious and potentially frustrating thing, that needed to be noted.
