### ISSUE TITLE
User-Agent header should be compared lower-case

### ISSUE THREAD

**Issue by evilpie** [mdn/webextensions-examples#158]
Maybe I am doing something wrong, but the User-Agent header in requestHeaders seems to be always in lower case for me. I.e. this code https://github.com/mdn/webextensions-examples/blob/master/user-agent-rewriter/background.js#L27 needs to be fixed.

**Comment by andymckay** [comment]
Works for me in clean Firefox 50.0.2. What browser version does it occur for you?

**Comment by evilpie** [comment]
I believe this changed in Firefox 52: 
https://hg.mozilla.org/mozilla-central/annotate/8103c612b79c2587ea4ca1b0a9f9f82db4b185b8/toolkit/modules/addons/WebRequest.jsm#l167
https://bugzilla.mozilla.org/show_bug.cgi?id=1254204

**Comment by andymckay** [comment]
Hmm I tried fixing this locally and changing the user agent doesn't work. Wondering if bug 1254204 broke something else.

**Comment by andymckay** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1323036
