### ISSUE TITLE
Add homepage_url to manifest.json

### ISSUE THREAD

**Issue by anaran** [mdn/webextensions-examples#16]
While
[1223145 – homepage_url should be displayed in about:addons](https://bugzil.la/1223145)
will keep the URL from showing up in about:addons right away, this will be useful once that bug is fixed.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/17 and https://github.com/mdn/webextensions-examples/commit/48030e542011139355a4811ed8618067cdb7cec6
