### ISSUE TITLE
Convert mocha-client-tests from using chrome.* to browser.*

### ISSUE THREAD

**Issue by kumar303** [mdn/webextensions-examples#165]
re: https://github.com/mdn/webextensions-examples/tree/master/mocha-client-tests

The use of the `chrome.*` API should be converted to `browser.*`. See: https://mail.mozilla.org/pipermail/dev-addons/2016-October/002025.html

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/262. Thanks @zlatin !
