### ISSUE TITLE
Convert react-es6-popup from using chrome.* to browser.*

### ISSUE THREAD

**Issue by kumar303** [mdn/webextensions-examples#166]
re: https://github.com/mdn/webextensions-examples/tree/master/react-es6-popup

The use of the `chrome.*` API should be converted to `browser.*`. See: https://mail.mozilla.org/pipermail/dev-addons/2016-October/002025.html

**Comment by kumar303** [comment]
I won't have time for this until after we launch the new AMO mobile V1

**Comment by viswanathamsantosh** [comment]
I will work on this issue this weekend!

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/262. THanks @zlatin !
