### ISSUE TITLE
Content scripts not working on https://addons.mozilla.org

### ISSUE THREAD

**Issue by onemen** [mdn/webextensions-examples#168]
None of the content script examples are working on https://addons.mozilla.org

**Comment by lidel** [comment]
I think it is already addressed in https://github.com/mdn/webextensions-examples/pull/160/files

**Comment by onemen** [comment]
So we can expect that any extension can fail on any page that uses the same feature.

**Comment by lidel** [comment]
No, only on pages that are in "exclude list":

> Content scripts are currently disabled on certain core Mozilla sites for security reasons.  -- [src](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082#c3)

**Comment by wbamberg** [comment]
@lidel is right. Thanks for filing, but this is a known thing that's already been noted.

**Comment by 7ERr0r** [comment]
Currently `extensions.webextensions.restrictedDomains` lists:

```
accounts-static.cdn.mozilla.net
accounts.firefox.com
addons.cdn.mozilla.net
addons.mozilla.org
api.accounts.firefox.com
content.cdn.mozilla.net
discovery.addons.mozilla.org
install.mozilla.org
oauth.accounts.firefox.com
profile.accounts.firefox.com
support.mozilla.org
sync.services.mozilla.com
```
