### ISSUE TITLE
Keep popup visible when file uploading is active

### ISSUE THREAD

**Issue by gladisihor** [mdn/webextensions-examples#169]
Hello,

I created my small extension and I've got some troubles in Firefox with file input inside my popup. I try to upload images by using this file input inside my popup and when file upload dialog is opened my popup hide out. For example in Chrome it works well, popup stays opened when file upload dialog is active.
Could you say please, how can I keep popup visible when file uploading is active?
([http://prntscr.com/doi67k](http://prntscr.com/doi67k))

**Comment by wbamberg** [comment]
Hi @gladisihor ! This issue is being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1292701.
