### ISSUE TITLE
page-to-extension-messaging: example page returns 404 error

### ISSUE THREAD

**Issue by nturcot** [mdn/webextensions-examples#174]
Hello,

[page-to-extension-messaging](https://github.com/mdn/webextensions-examples/tree/master/page-to-extension-messaging) example is supposed to rely on the following page according to README instructions: https://mdn.github.io/webextensions-examples/content-script-page-script-messaging.html
...but it returns a 404 error.

If the page is somewhere else, both README.md and manifest.json need to be updated.

**Comment by wbamberg** [comment]
Thanks for filing! That's strange. This page used to live in the gh-pages branch of this repo, but I can't see that branch at all any more.

**Comment by wbamberg** [comment]
It should be fixed now. @nturcot , please can you check it works for you?
