### ISSUE TITLE
native-messaging - Native application tried to send a message of 977472013 bytes, which exceeds the limit of 1048576 bytes.

### ISSUE THREAD

**Issue by mpbaran** [mdn/webextensions-examples#178]
Hi,
I've got a problem with **native-messaging** example. I was trying to connect with some simple JAVA application. Java application received the message sent from add-on but on browser consol i've got error like in issue subject, and there wasn't answer sent from my Java app.

> Native application tried to send a message of 977472013 bytes, which exceeds the limit of 1048576 bytes.  NativeMessaging.jsm:238
> 	_startRead/this.readPromise<                             resource://gre/modules/NativeMessaging.jsm:238:17

From Chrome browser communication is correct...

Have you got any idea of this problem with communication....

[my-add-on.zip](https://github.com/mdn/webextensions-examples/files/741869/my-add-on.zip)

**Comment by andymckay** [comment]
So this isn't a problem with the example, but with your code? There are other ways to contact us as listed here: https://wiki.mozilla.org/Add-ons#Getting_in_touch

As for your problem, is that you are exceeding a limit set in Firefox here: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/NativeMessaging.jsm#274

If you think that limit should be raised, please file a bug in Bugzilla, or change your native application.
