### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#18]
We should have some basic guidance for people who want to add new examples or improve existing ones.

**Comment by anaran** [comment]
For third parties following this issue [this discussion about CONTRIBUTING.md](https://github.com/mdn/webextensions-examples/pull/11#issuecomment-155159035) might also be useful.

**Comment by wbamberg** [comment]
Closed by https://github.com/mdn/webextensions-examples/pull/27.
