### ISSUE TITLE
Create example showing what different types of windows look like

### ISSUE THREAD

**Issue by kumar303** [mdn/webextensions-examples#189]
The docs on [the types of windows that can be created](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/CreateType) doesn't have any screenshots so I was looking for examples. The only one I see is [window-manipulator](https://github.com/mdn/webextensions-examples/tree/master/window-manipulator) but that doesn't show what the different types of panels look like. We should add an example showing all these types of windows.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/217#pullrequestreview-37171928.
