### ISSUE TITLE
[Q] What is "mobile" folder with id="mobile______" in bookmark list?

### ISSUE THREAD

**Issue by dehghani-mehdi** [mdn/webextensions-examples#190]
Hi,

I'm sorry if I'm in wrong place to ask this question, if you know some reference about Web Extraction's API, specially about bookmark, please tell me.

And if ask the question would be great.

Also is there any way to ignore default bookmark folder (such as Bookmarks toolbar & ...) _actually how I can get the list of user created folder(s)?_

Thank you.

**Comment by andymckay** [comment]
I'm sorry I don't understand the question, the API for bookmarks is here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks.

**Comment by dehghani-mehdi** [comment]
Don't worry.
I read MDN article.

Based on sample code of [bookmarks.getTree()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/getTree), I want to get all `User create folder(s)`, so I wrote:

    if(!bookmarkItem.url) console.log(bookmarkItem.title);

I got `Bookmarks Toolbar, Other Bookmarks, .... & mobile`. I have no idea what `mobile` is, I can see that in `bookmark menu`, so I tired to log `bookmarkItem` instead, then I found out the `Id` of `mobile` is `mobile______`, looks like it's special folder or something, the point is this folder didn't create by user (actually I tested the code on my pc & I'm sure I have no folder named mobile).

So the question is, __how I can get user created folder list?__

btw, as I using `web-ext` tool, when I use `web-ext run --firefox="C:\Program Files\Mozilla Firefox\firefox.exe"`, the tool open up new instance of Firefox, with new profile, so there is no user created folder.

**Comment by andymckay** [comment]
This isn't a support forum, but for reporting bugs about the examples. Please the mailing list or discourse for these kinds of questions:

https://wiki.mozilla.org/Add-ons#Getting_in_touch

If you feel Firefox has a bug or needs a feature, then please file a bug at https://bugzilla.mozilla.org, under Toolkit > WebExtensions.

**Comment by andymckay** [comment]
Just saw this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1341541, might be relevant.
