### ISSUE TITLE
Cannot send/receive messages between background and content after reloading addon

### ISSUE THREAD

**Issue by mchubby** [mdn/webextensions-examples#197]
Hi,

There is an error logged in Browser console **after reloading a temporary addon** and use of `browser.tabs.sendMessage` or `browser.runtime.sendMessage`
```
Error: Could not establish connection. Receiving end does not exist.         (unknown)
```

reproduced in FX 52 and 54.0a2 with steps:

- create a blank profile and start it, close all extra tabs
- Load an https URL
- open `about:debugging` in a new tab
- load a temporary add-on that uses message communication. For instance, cookie-bg-picker/manifest.json
- Click on reload button
- Switch to initial https tab
- Click on browser action ui and select a background

Expected:
background has changed

Actual:
nothing happens

- Open (Ctrl+Shift+J) browser console to see diag message

Notes:
seems to be the same when installing `cookie_bg_picker-1.0-an+fx.xpi` twice.

**Comment by wbamberg** [comment]
Thanks for filing, and for nice clear steps to reproduce, and sorry to take so long to look at this. I've made a PR that should fix this: https://github.com/mdn/webextensions-examples/pull/212.

**Comment by wbamberg** [comment]
Fixed: https://github.com/mdn/webextensions-examples/pull/212
