### ISSUE TITLE
Each add-on should indicate the minimum Firefox version it needs

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#20]

**Comment by johannhof** [comment]
It should be supported to specify that in the manifest once we find out if [Bug 1192437](https://bugzilla.mozilla.org/show_bug.cgi?id=1192437) is already implemented or not. :smile:

**Comment by wbamberg** [comment]
Thanks @johannhof ! I've added strict_min_version to all the examples.

**Comment by johannhof** [comment]
:+1:
