### ISSUE TITLE
Beastify doesn't work with Firefox 45.0a2 (2016-01-03)

### ISSUE THREAD

**Issue by arnaud-jacquemin** [mdn/webextensions-examples#21]
Hello,

When I run the "Beastify" addon on Firefox Developer Edition 45.0a2 (2016-01-03), the "paw" icon is there, it opens the popup with 3 buttons, but nothing happens when I click these buttons.

Looking at my OS console, I found this messages :

> Extension error: Error opening input stream (invalid filename?): moz-extension://b4f0c458-8e3b-4aa8-bb3c-5ff7d692969b/popup/content_scripts/beastify.js undefined undefined
> [[Exception stack
> undefinedCurrent stack
> runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:25:110
> tryInject@resource://gre/modules/ExtensionContent.jsm:191:9
> execute@resource://gre/modules/ExtensionContent.jsm:267:5
> executeScript@resource://gre/modules/ExtensionContent.jsm:387:5
> receiveMessage@resource://gre/modules/ExtensionContent.jsm:590:9
> ]]

The addon now works if I change a line in the [popup/choose_beast.js](https://github.com/mdn/webextensions-examples/blob/master/beastify/popup/choose_beast.js) source code, from : 
```javascript
  chrome.tabs.executeScript(null, {
    file: "content_scripts/beastify.js" 
  });
```

to :
```javascript
  chrome.tabs.executeScript(null, {
    file: "../content_scripts/beastify.js" 
  });
```

I don't know if it's a Firefox bug or a typo in the Beastify source code ?

Thank you in advance

**Comment by rpl** [comment]
@wbamberg @arnaud-jacquemin it looks like a Firefox bug (I tried on a Chromium based browser and it works correctly, and it fails if the workaround is applied)

I've filed it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1236500

**Comment by wbamberg** [comment]
Thanks @rpl ! I'll leave this open until the fix is in Nightly and we have verified that it works.

**Comment by wbamberg** [comment]
I've implemented the workaround for now: https://github.com/mdn/webextensions-examples/commit/315084cf47d53993dbcc7aa377ac04f03d24f4b3 and will take it out when the bug is fixed.

**Comment by arnaud-jacquemin** [comment]
Thank you guys!

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/26. Thanks @rpl and @arnaud-jacquemin .
