### ISSUE TITLE
Add a submenu

### ISSUE THREAD

**Issue by boxconnect** [mdn/webextensions-examples#211]
Not an actual issue but was looking for a way to implement a submenu?

**Comment by wbamberg** [comment]
If you create more than one item, they're automatically placed in a submenu whose parent is the name of the add-on. To create an item in a submenu under another item you created, pass the parent's ID as `parentId` in the `createProperties` object passed into [`contextMenus.create()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus/create).
