### ISSUE TITLE
getRedirectURL

### ISSUE THREAD

**Issue by transfluxus** [mdn/webextensions-examples#238]
Hi,

I am trying to make an extension that connects to twitter via oauth.
Since I need a redirect URL I looked into the google-info example that contains the line:
`browser.identity.getRedirectURL();`
this doesn't work in my extension. `browser.identity` doesn't even exist...
I also added identity to the permissions

do i need to add something else?

**Comment by wbamberg** [comment]
Please ask general support questions in the Discourse forum: https://discourse.mozilla-community.org/c/add-ons/development.
