### ISSUE TITLE
tabs-tabs-tabs: highlight looks like do nothing

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mdn/webextensions-examples#241]
Chromium 61 developer build or Chrome 59, with dark theme or default. MacOS.

**Comment by wbamberg** [comment]
Please see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#JavaScript_APIs. These examples use the `browser` namespace and promises, where Chrome uses the `chrome` namespace and callbacks.

This polyfill: https://github.com/mozilla/webextension-polyfill ought to make the example work in Chrome, but I haven't tried it.

**Comment by wbamberg** [comment]
Although the code does say this: https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/tabs.js#L163, which is misleading.
