### ISSUE TITLE
eliminate `getting` intermediate variables

### ISSUE THREAD

**Issue by yfdyh000** [mdn/webextensions-examples#242]
I think they will bring bad habits for cumbersome coding, although they have a little semantic effect.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1373152

**Comment by wbamberg** [comment]
As the eslint person says in the linked bug, I think this is a subjective thing, and not a thing we should eradicate.

It's also worth thinking that this repo isn't a single unitary codebase, where a high degree of consistency is desirable even between options that are equally good. It's a collection of examples, and as such I think there's actually some benefit to showing how extensions can be written using a variety of styles, as long as they're all reasonably good practice.
