### ISSUE TITLE
Need example for using Embedded WebExtensions in an overlay add-on

### ISSUE THREAD

**Issue by Rob--W** [mdn/webextensions-examples#245]
The feature introduced in https://bugzilla.mozilla.org/show_bug.cgi?id=1252215 and documented at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions can also be used by an overlay add-on. There is however no official sample code.

@rpl Could you upstream your example at https://github.com/rpl/webextensions-examples/tree/example/embedded-webextension-overlay/embedded-webextension-overlay ?
@wbamberg Could you update the MDN article once @rpl has submitted a PR that gets merged?

**Comment by andymckay** [comment]
Given that Embedded WebExtensions won't be available in Firefox 57, I'm not sure we should have any more examples of this.

**Comment by Rob--W** [comment]
It's still 4 weeks away until Nightly, and 18 until release. There are also
overlay add-ons that need to be ported before that, and this kind of add-on
is distinct enough to warrant its own example.

**Comment by andymckay** [comment]
I suppose we do have https://github.com/mdn/webextensions-examples/tree/47a9c3b34b85453240bcb373b5e2a3a5faa94163/embedded-webextension-bootstrapped in this repo. Whilst that remains around, seems like a valid thing to ask for.

**Comment by YoruNoHikage** [comment]
I'm actually trying to port an overlay add-on to WebExtension. How can this be done?
