### ISSUE TITLE
What's the type of demo "embedded-webextension-sdk"?

### ISSUE THREAD

**Issue by zhaihm** [mdn/webextensions-examples#257]
The following official demo:
https://github.com/mdn/webextensions-examples/tree/master/embedded-webextension-sdk/step1-hybrid-addon

Its name is *hybrid* add-on. But I see package.json and main.js in it. I assume this is still a JSCTypes add-on (not WebExtensions), right?

Another question, is it allowed to use legacy add-on SDKs inside a WebExtensions add-on? Some of features are not implemented for WebExtensions yet, so I think could I use old SDKs as a workaround?

**Comment by yfdyh000** [comment]
> I assume this is still a JSCTypes add-on (not WebExtensions), right?

No, it is https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions

"The embedded WebExtension's files are packaged inside the legacy add-on."
"Firefox 57 drops support for legacy add-on types, including legacy add-ons that embed WebExtensions."

**Comment by zhaihm** [comment]
@yfdyh000 Thanks, that answered my question!
