### ISSUE TITLE
Installing examples through add-on manager

### ISSUE THREAD

**Issue by Aris-t2** [mdn/webextensions-examples#261]
Why WE examples have to be installed through 'about:debugging' and not like a normal xpi/zip files through add-on manager (in the past)? 
Firefox always shows a warning "This add-on could not be installed. It appears to be corrupt".

Why there are there such restrictions?

**Comment by wbamberg** [comment]
> Why WE examples have to be installed through 'about:debugging' and not like a normal xpi/zip files through add-on manager (in the past)?

They don't. You can install them as XPI files, as long as they are signed (or you are running Nightly and have disabled the signing requirement, which AFAIK is still possible).

The "build" directory contains built XPIs for most of the extensions in this repo (although we are not very good at keeping it updated) and I just checked that at least the "beastify" XPI installs on Firefox 57.

If you're having a problem with a particular XPI, it's probably best to ask in the Discourse forum: https://discourse.mozilla.org/c/add-ons/development.

**Comment by Aris-t2** [comment]
Tried a few xpi files from builds directory and a few "selfmade" from available files. In every case the installation failed on Firefox 57 (xpinstall.signatures.required is set to false) with "This add-on could not be installed. It appears to be corrupt". Test it with ApplyCSS for example.

The only workaround was adding this to manifest.json

	"applications": {
		"gecko": {
			"id": "testaddon@testid",
			"strict_min_version": "56.0"
		}
	}

Windows 7 x64, Firefox 57 x64.

**Comment by wbamberg** [comment]
Oh, yes, that's true. Please see:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID.
