### ISSUE TITLE
Longer URL is not supported

### ISSUE THREAD

**Issue by achayan** [mdn/webextensions-examples#265]
I think if a url is longer than 150 char then this snippet won't work. for example https://productforums.google.com/forum/#!topic/adsense/gcuWmHA7n3s;context-place=topicsearchin/adsense/authorid$3AAPn2wQdpgvH-5r3cGWSJImFm-5C5DV5tuVAF_UNQVXqeSREfExYqi3v1_SKbw7EY8Hw63FL5TUBR%7Csort:date%7Cspell:false in this topic there is a long url but this exmple fail to copy the whole link. This probably the linked to https://bugzilla.mozilla.org/show_bug.cgi?id=1338898

**Comment by wbamberg** [comment]
Thanks for filing. Which example exactly doesn't work, and what are the steps to reproduce?

I tried https://github.com/mdn/webextensions-examples/tree/master/context-menu-copy-link-with-types and it seemed to work fine with that URL, on Firefox 55.

**Comment by wbamberg** [comment]
Closing, as this isn't actionable without more information.
