### ISSUE TITLE
Add webRequests Example

### ISSUE THREAD

**Issue by Miserlou** [mdn/webextensions-examples#267]
I'm looking to build an extension which needs to inspect the contents of network requests made by a page. I think that I need to use `webRequests` to do this, but there are no examples in this repo which use `webRequests`. I have been able to find this, which is quite good, but it'd be nice if we could have this example or one like it in this repo: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Intercept_HTTP_requests

**Comment by wbamberg** [comment]
@Miserlou, there are a couple of examples that use webRequest:

https://github.com/mdn/webextensions-examples/tree/master/stored-credentials
https://github.com/mdn/webextensions-examples/tree/master/user-agent-rewriter

Is there anything else in particular you need an example of?

In general, this page: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples should help you find which examples use which APIs.

**Comment by Miserlou** [comment]
My bad, I did an `ag` for `webRequests`, rather than `webRequest`, and didn't find your examples. Thanks.
