### ISSUE TITLE
Proxy-blocker not working

### ISSUE THREAD

**Issue by kanowins** [mdn/webextensions-examples#268]
Can't make it work with Firefox 56.0b2 32 bits and 64 bits.

I install the extension and it doesn't block example.com. Also, I change the banned sites on about:addons and new added sites are not blocked neither.

I have tested a bit the code and I'm almost sure that the problem is  browser.runtime.sendMessage(storedSettings.blockedHosts, {toProxyScript: true}); is not sending the message to the pack file.

Perhaps I'm doing something wrong.

**Comment by wbamberg** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1389459.
