### ISSUE TITLE
How to port "Intercepting Page Loads"

### ISSUE THREAD

**Issue by Miserlou** [mdn/webextensions-examples#271]
There is a page on the Mozilla wiki about [Intercepting Page Loads](https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Intercepting_Page_Loads) - unfortunately, this of course now outdated, but I have no idea how to port these concepts.

The problem is that `webRequest` does not differential between items loaded on a page and the load of a deliberately-visited page itself. I've read through all of the events in this repo and I don't see anyway to differentiate between page loads and contents on a page.

Is there a way to intercept a deliberately loaded page before it loads, without having to inspect in-transit HTTP requests?

[Sorry if I'm using this project's issue's page inappropriately, if you could be so kind as to direct me to a better forum for these types of questions I'd appreciate it!]

**Comment by andymckay** [comment]
Please use the mailing list dev-addons: https://mail.mozilla.org/listinfo/dev-addons to ask this sort of question. Thanks.
