### ISSUE TITLE
No guide into submitting webpack extensions to AMO

### ISSUE THREAD

**Issue by losnappas** [mdn/webextensions-examples#276]
Took me a bit longer than I'd like to realize that there's a "Submit source code with the extension" thingy in the AMO submit form. Nowhere does it say that such a thing exists in the 'webpack-modules' example and looking at the image [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension), it appears as if you're supposed to submit everything in one zip. You aren't.

Just adding "You can submit the source code at AMO separately" to the webpack example would surely one day save like 10 minutes of someone elses time, if not more! amazing

**Comment by pmario** [comment]
I let "web-ext" cli do the stuff for me. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext#Packaging_your_extension
