### ISSUE TITLE
Style attribute bug in Beastify example.

### ISSUE THREAD

**Issue by changx03** [mdn/webextensions-examples#280]
In beastify.js file, the 2nd line setAttribute overwrites the 1st one, so the 1st one never been used.
change
beastImage.setAttribute("style", "width: vw");
beastImage.setAttribute("style", "height: 100vh");
to 
beastImage.setAttribute("style", "width: vw;height: 100vh");

**Comment by wbamberg** [comment]
Thanks for filing! Yes, I know :(. There's a PR to fix this that I need to update: https://github.com/mdn/webextensions-examples/pull/240.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/240.
