### ISSUE TITLE
context-menu-demo is missing

### ISSUE THREAD

**Issue by c-yan** [mdn/webextensions-examples#289]
context-menu-demo which is linked in README.md is missing.

<dl><dt><a href="https://github.com/mdn/webextensions-examples/tree/master/context-menu-demo">context-menu-demo</a></dt>
<dd>Adds items to the context menu.</dd>
</dl>

**Comment by wbamberg** [comment]
Oh, thanks. It moved to [menu-demo](https://github.com/mdn/webextensions-examples/tree/master/menu-demo), but we should update the README.

**Comment by wbamberg** [comment]
On second thoughts, I just removed this index from the README, and pointed people at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples instead. It's hard enough keeping the list up to date when we only have to do it in one place :).
