### ISSUE TITLE
borderify needs a review

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#29]
https://github.com/mdn/webextensions-examples/tree/master/borderify

**Comment by bwinton** [comment]
* I think we should add a README, describing the add-on, and what it's trying to demonstrate.  (It could just be a link to the relevant MDN page, if you'ld prefer.

Other than that, shipit!  :shipit:

**Comment by wbamberg** [comment]
I've just pushed https://github.com/mdn/webextensions-examples/commit/f98638396bcba2fe9f0a934a1ad6da00d45157d9 for this.
