### ISSUE TITLE
Overwriting Browser CSS

### ISSUE THREAD

**Issue by jonathan-s** [mdn/webextensions-examples#293]
In the readme for a [dynamic theme](https://github.com/mdn/webextensions-examples/blob/master/dynamic-theme/README.md) it tells you how you can edit a theme on the fly which is create. But it would be even better if there also was a link to all the CSS that you could overwrite, or some explanation of where you can find that CSS.

**Comment by wbamberg** [comment]
The changes you can make using the theme API are documented on MDN: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme. Is this what you are talking about? We could certainly add a link to that page from the dynamic theme README.
