### ISSUE TITLE
beastify extension does not work on first click on some sites

### ISSUE THREAD

**Issue by jeffhunter** [mdn/webextensions-examples#297]
1. Launch Firefox 56.0 or 57.0 beta 7.
2. Load beastify extension on about:debugging page.
3. Go to the following URL:

http://www.plainchicken.com/2017/10/breakfast-potato-skins.html

4. Click beastify button in browser toolbar.
5. Click on Frog.
(Nothing happens.)
6. Click on Frog again.
(Frog image is shown.)

I expect the Frog to be shown the first time I click, but it's not. The URL above is just an example, this also happens with other sites too. The more complex and ad-heavy the site, the more likely this will happen.

**Comment by wbamberg** [comment]
Thanks for filing! I think https://github.com/mdn/webextensions-examples/pull/240 will fix this.

**Comment by jeffhunter** [comment]
I have not looked at #240 in full detail, but I think the call to `browser.tabs.executeScript()` in beastify should probably be passing the `runAt` parameter with a value of `"document_start"` for additional robustness:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extensionTypes/RunAt

**Comment by wbamberg** [comment]
This should be fixed by https://github.com/mdn/webextensions-examples/pull/240.

I didn't use `runAt` here. I think this is an edge case, and I think it could cause some other problems.
