### ISSUE TITLE
notify-link-clicks-i18n needs a review

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#30]
https://github.com/mdn/webextensions-examples/tree/master/notify-link-clicks-i18n

**Comment by bwinton** [comment]
* We should have a README, with some details about the add-on, and what it's demonstrating.
* I feel like the `addListener`s should be below the things they're adding as listeners.

Other than that, LGTM.

**Comment by wbamberg** [comment]
Thanks @bwinton ! Just pushed https://github.com/mdn/webextensions-examples/commit/bba84627abed98c293989a93290b853733356eac.
