### ISSUE TITLE
reate a webextension who open and read a zim file

### ISSUE THREAD

**Issue by mothsART** [mdn/webextensions-examples#306]
Hi, 

I'd like to create a webextension who open a zim file. 
Someone can explain to me how i need to tell to firefox that he can open it and how can i mention that is my extension who must do it. 

My actual solution (dirty) : 
a python script who 
1.decode zim file and extract all files in a temp directory. 
2. launch firefox with the index.html 

Open in browser : https://addons.mozilla.org/en-us/firefox/addon/open-in-browser/
do the job but is not using webextensions.
What about fileBrowserHandler API (https://developer.chrome.com/extensions/fileBrowserHandler)  in Firefox ?

**Comment by andymckay** [comment]
This isn't an appropriate place for this kind of question. Please use discourse https://discourse.mozilla.org/c/add-ons or https://mail.mozilla.org/listinfo/dev-addons.
