### ISSUE TITLE
notify-link-clicks needs a review

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#31]
https://github.com/mdn/webextensions-examples/tree/master/notify-link-clicks

**Comment by bwinton** [comment]
Do we need this, since we've got an i18n version which demonstrates the same things with minimal extra complexity?

**Comment by wbamberg** [comment]
Nope, we don't. Good point! https://github.com/mdn/webextensions-examples/commit/078ef0e1f3ec93ae75fc843084188330c48eff0f.
