### ISSUE TITLE
Sample for dev tools console explorer handling

### ISSUE THREAD

**Issue by kabilanvk** [mdn/webextensions-examples#311]
Does any sample deal with Dev tools console view? if not can we have one similar to https://addons.mozilla.org/en-US/firefox/addon/consoleexport/.

**Comment by wbamberg** [comment]
As far as I know, WebExtensions don't support interacting with the console: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Extending_the_developer_tools.
