### ISSUE TITLE
selection-to-clipboard's README has broken link

### ISSUE THREAD

**Issue by c-yan** [mdn/webextensions-examples#312]
There is a broken link on https://github.com/mdn/webextensions-examples/blob/master/selection-to-clipboard/README.md

[Interact with the clipboard](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard.)

It seems to be due to the dot at the end of the URL.

**Comment by wbamberg** [comment]
Thanks, fixed!
