### ISSUE TITLE
[download.downloads] It's hard to find out the actual value of the browser download directory setting

### ISSUE THREAD

**Issue by pmario** [mdn/webextensions-examples#314]
If I'm missing something obvious, please point me to the right direction. 

Thank you for your great work!

Issue: 

 - It's hard to find out the actual value of the browser download directory setting, and there are no examples similar to my usecase. 

Usecase: 
 
 - Using a `file:///*` URI
 - Create a web extension, that downloads a file, overwriting an existing file. 
 - If the downloaded file is in the browser downloads directory everything is relatively simple. 
 - If the file is stored in a `downloads/subdirectory` things get complicated, 

Expected: 

 - It should be easy to determine the existing downlaod folder setting. 
 - eg: [downloads.DownloadItem](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/DownloadItem) should contain a new property
 - property name: `relativeFilename` that contains the result similar to nodejs [path.relative() function](https://nodejs.org/api/path.html#path_path_relative_from_to)
    - eg: `./subdir/myname.html` for unix or `.\\subdir\\myname.html` for win, since this value could be directly reused.

MTC for the usecase. 

 - see: https://github.com/pmario/download-mtc

**Comment by wbamberg** [comment]
I think this is not currently supported in the WebExtensions API, so the best thing to do would be to file a bug: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions%3A%20Untriaged asking for it.

If I've misunderstood and there is in fact a way to do this, please feel free to reopen here, and we can add it to one of the examples.

**Comment by pmario** [comment]
Just for my reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1420586
