### ISSUE TITLE
browser.tabs.create - different behaviour between windows and linux

### ISSUE THREAD

**Issue by pmario** [mdn/webextensions-examples#315]
OS: win10 pro and ubuntu 17.10

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create at: "Browser compatibility" section for `createProperties.url` footnote 1 for "edge" browser states:

> 1. If the url has the 'ms-browser-extension://' protocol it is mistakenly considered a relative URL and the prefix is added redundantly, causing tab to fail loading.

See: "mistakenly" above. ... but FF on ubuntu shows the same "mistake" .... 

**To reproduce**

 - Download MTC: https://github.com/pmario/open-tab-mtc ... 
 - Activate the AddOn as a temporary AddOn
 - Open the file open-tab.html in the browser.
 - Click "Save and open New Tab" button .... win -> OK ... ubuntu ... -> wrong

How can I fix this?

**Comment by wbamberg** [comment]
I'm not quite sure what the problem is here. Is it that Firefox won't open "ms-browser-extension://" URLs? I wouldn't expect it to.

> To reproduce
> 
>     download MTC: https://github.com/pmario/download-mtc ...
>     open quine.html, which is part of the repo
>     click "Let's start" button .... win -> OK ... ubuntu ... -> wrong

This isn't a minimal test case for the issue.

**Comment by pmario** [comment]
The problem with FF for ubuntu is, that it prefixes the file URI with: `moz-extension://8e990525-fe39-47ae-a18b-d5f378a8d716` ... Which was considered a mistake for edge. .. So it must be a mistake for FF with ubuntu too. right?

>This isn't a minimal test case for the issue.

OK. I made a smaller one: https://github.com/pmario/open-tab-mtc  .. with less UI

I did also fix / change the instructions and the link in the OP

**Comment by pmario** [comment]
The URI on ubuntu looks like this: `moz-extension://8e990525-fe39-47ae-a18b-d5f378a8d716/home/mario/Downloads/new-tab.html`

When I remove the `mox-extension` stuff like so: `/home/mario/Downloads/new-tab.html`  the file loads as expected with: `file:///home/mario/Downloads/new-tab.html`

**Comment by wbamberg** [comment]
This is still not a minimal test case.

Please confirm:

* what is the argument you are passing into tabs.create
* where on disk the file you are trying to load is located
* what happens on the different operating systems

As the docs say, you should not be able to pass file:// URLs into tabs.create. You can pass a URL that references a file included with your extension. To do this: "specify an absolute URL starting at the extension's manifest.json file".

**Comment by pmario** [comment]
ok ... I'll need to change the workflow.
