### ISSUE TITLE
How to override key command

### ISSUE THREAD

**Issue by mbokil** [mdn/webextensions-examples#321]
I'm writing a kiosk extension. I have the fullscreen and options screens working well. I haven't been able to find an example of overriding default key commands. Commands like quit, show dev tools, etc I would need to intercept. Used to be able to do it in XUL commands uncertain with webextensions.

**Comment by polyzen** [comment]
This comment provides details: https://bugzilla.mozilla.org/show_bug.cgi?id=1215061#c66

**Comment by wbamberg** [comment]
Thanks @polyzen . Closing this, since it's not possible to provide an example (yet).
