### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by thardes2** [mdn/webextensions-examples#326]
Maybe I don't see the important aspect, but there are not Icons displayed in the the menu bar - in Chrome, it works.
![image](https://user-images.githubusercontent.com/6141477/33930069-f8941224-dfeb-11e7-91d3-5565b1654a38.png)
I know this works with 
`
  "browser_action": {
    "default_icon": {
      "16": "icons/page-16.png",
      "32": "icons/page-32.png"
    }
  }`
but why is this not added to the examples?

**Comment by wbamberg** [comment]
Thanks for filing!

This extension adds a [page action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Page_actions) icon, which shows up in the URL bar, and does not show up in about: pages such as "about:addons". The reason it appears in Chrome is that Chrome always shows an icon for all installed extensions, whether or not the extension adds a button in the toolbar.

Having said that, it doesn't actually specify an icon, so you just get the default "puzzle piece" icon. I've filed https://github.com/mdn/webextensions-examples/pull/327 to add a proper icon.

**Comment by wbamberg** [comment]
-> https://github.com/mdn/webextensions-examples/pull/327
