### ISSUE TITLE
Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by soapdog** [mdn/webextensions-examples#329]
This is related to the native messaging sample.

I am running macOS X and Firefox Nightly 59. I have the app manifest in the correct location and the application file has the executable path. The same sample is working on my Windows 10 machine (after I added the regedit stuff). The paths inside the JSON files are also correct.

Can someone double check it on recent nightly?

**Comment by wbamberg** [comment]
It works for me on OS X, with 59.0a1 (2017-12-12).

**Comment by soapdog** [comment]
Apparently the problem was with `env python` on the shebang line on my machine. Changing it to a path to python solved it.

**Comment by willm** [comment]
This fixed it for me, shouldn't the `#!` line be changed?
