### ISSUE TITLE
How to message pass btw Popup.html to contentscript

### ISSUE THREAD

**Issue by sriharrsha** [mdn/webextensions-examples#338]
It is working for firefox but not in Chrome

**Comment by wbamberg** [comment]
Are you referring to a specific example in this repo? If so, could you let me know:
(1) which one
(2) what you tried to do
(3) what you expected to happen
(4) what happened

If you're asking a general support question, please ask in the [add-ons forum](https://discourse.mozilla.org/c/add-ons/development), not here.

**Comment by sriharrsha** [comment]
I was using v 0.2.0 .This issue was fixed in 0.2.1 version
