### ISSUE TITLE
Incorrect version number in private browsing theme for AMO

### ISSUE THREAD

**Issue by spikespaz** [mdn/webextensions-examples#341]
This issue was originally posted at the [addons-linter issue](https://github.com/mozilla/addons-linter/issues/1848).

The version number in the [private browsing theme](https://github.com/mdn/webextensions-examples/tree/master/private-browsing-theme) example (`"strict_min_version": "57.0b14"`) does not match any of the [known version numbers on AMO](https://addons.mozilla.org/en-us/firefox/pages/appversions/).

It should be changed to `"strict_min_version": "57.0"`.

I am unaware of how many other examples have this issue, however it was misleading for a newcomer creating a [theme](https://github.com/spikespaz/firefox-nativedark/commit/5c806344a199ebd66c4d54aeab2c505cfaf4e696).

**Comment by wbamberg** [comment]
Thanks for filing!
-> https://github.com/mdn/webextensions-examples/pull/342 should fix it.
