### ISSUE TITLE
browser.webRequest.filterResponseData cannt get complete body

### ISSUE THREAD

**Issue by ykjsw** [mdn/webextensions-examples#348]
hi, i use the code: https://github.com/mdn/webextensions-examples/blob/master/http-response/background.js
in my firefox addon, and i find sometimes i cannt get the complete body, 
I listen in the post xhr request

can any one help me?

**Comment by wbamberg** [comment]
Thanks for filing!

Unless you think there is an actual bug in the example, it's best to raise issues with developing WebExtensions in the forum: https://discourse.mozilla.org/c/add-ons/development, not here.
