### ISSUE TITLE
Remove embedded webextensions examples

### ISSUE THREAD

**Issue by nt1m** [mdn/webextensions-examples#349]
They aren't supported since Firefox 57.

**Comment by wbamberg** [comment]
@aswan , what do you think? I don't really see a use for these any more.

**Comment by aswan** [comment]
We still use a few of these internally (e.g., screenshots) but we're working on getting rid of them.  +1 from me but lets also get an opinion from @rpl

**Comment by rpl** [comment]
@wbamberg @aswan +1 from me to on getting rid of them right now 
(no new extension should be written this way internally, they can now be written as "webextensions with an embedded experiment API", the internal ones that still uses it are going to get rid of it in the near future, and for third party extensions it is something that is already not supported from Firefox 57).

**Comment by caitmuenster** [comment]
Is this issue still open? If we still have examples of Embedded WebExtensions, they should be removed. 

// cc @irenesmith

**Comment by irenesmith** [comment]
I believe I approved and mreged a PR to remove them but I will look into it.

**Comment by SalvatoreMeschini** [comment]
I guess that this issue can be closed, Embedded* folders are no longer available by downloading the ZIP snapshot.

**Comment by wbamberg** [comment]
Yes, thanks @SalvatoreMeschini !
