### ISSUE TITLE
native-messaging `Native application tried to send a message of 1635017060 bytes, which exceeds the limit of 1048576 bytes.`

### ISSUE THREAD

**Issue by mantou132** [mdn/webextensions-examples#353]
i create a js file, used to replace `ping_pong.py`:
```
#!/usr/bin/env -S -P /usr/local/bin:/usr/bin:${PATH} node
process.stdin.setEncoding('utf8');
process.stdin.on('readable', () => {
  const chunk = process.stdin.read();
  if (chunk !== null) {
    console.log(`data: ${chunk}`);
  }
});
process.stdin.on('end', () => {
  process.stdout.write('end');
});
```
then modify [Native messaging manifests](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_manifests).

Always get an error: `Native application tried to send a message of 1635017060 bytes, which exceeds the limit of 1048576 bytes.`

**Comment by wbamberg** [comment]
This tracker is specifically for bug in the example extensions contained in this repo.

For general help with WebExtensions please use the Discourse forum: https://discourse.mozilla.org/c/add-ons/development.
