### ISSUE TITLE
question for permissions

### ISSUE THREAD

**Issue by saturn721** [mdn/webextensions-examples#358]
Extention beastify don't work write error: Error: Missing host permission for the tab  undefined
Error: Could not establish connection. Receiving end does not exist.  undefined. manifest.json from example, and contains  "permissions": [  "activeTab" ].

**Comment by wbamberg** [comment]
beastify works for me:

* install it from the master branch of this repo in Firefox Nightly using about:debugging's "Load Temporary Add-on"
* open "example.com", click the browser action icon, select a beast.

Can you please let me know in detail exactly what you've tried and what happened?

**Comment by saturn721** [comment]
issue closed, I'm apologize. I tried to do it on the blank tab.

**Comment by wbamberg** [comment]
No problem, I'm glad it worked for you!
