### ISSUE TITLE
Have coverage for the 50 most popular APIs in the Chrome store

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#36]
Here's the list, courtesy of andym. I'll keep this report updated as we add new examples. When all entries are "done" or "not doing", this bug can be closed.

Of course, a single example add-on could (and probably should) demonstrate more than one API. So this does not necessarily mean that we need 50 examples.

**Remaining:**
```
chrome.runtime.onInstalled
chrome.runtime.getManifest
chrome.runtime.reload
chrome.webNavigation.onCommitted
chrome.webNavigation.onBeforeNavigate
```

**Done:**
```
chrome.browserAction.onClicked
chrome.browserAction.setBadgeText
chrome.browserAction.setBadgeBackgroundColor
chrome.browserAction.setTitle
chrome.browserAction.setIcon
chrome.contextMenus.create
chrome.contextMenus.onClicked
chrome.extension.getURL
chrome.extension.getBackgroundPage
chrome.i18n.getMessage
chrome.management.getAll
chrome.notifications.create
chrome.runtime.sendMessage
chrome.runtime.onMessage
chrome.runtime.connect
chrome.runtime.onConnect
chrome.storage.sync
chrome.storage.local
chrome.tabs.query
chrome.tabs.create
chrome.tabs.sendMessage
chrome.tabs.executeScript
chrome.tabs.onUpdated
chrome.tabs.update
chrome.tabs.onRemoved
chrome.tabs.reload
chrome.tabs.onCreated
chrome.tabs.get
chrome.tabs.onActivated
chrome.tabs.remove
chrome.windows.update
chrome.windows.getCurrent
chrome.windows.getAll
chrome.windows.create
chrome.webRequest.onErrorOccurred
```

**Not doing:**
```
chrome.tabs.getSelected (deprecated)
chrome.tabs.onReplaced (Chrome-only)
```

**Comment by wbamberg** [comment]
Removed deprecated `extension` APIs.

**Comment by wbamberg** [comment]
Updated, marked a couple more APIs as deprecated or unsupported.

**Comment by andymckay** [comment]
The following:

```
chrome.runtime.onInstalled
chrome.runtime.reload
```

Need a fully signed and installed add-on that then updates. We could do it on MDN or set it up all here. Is that worth it?

**Comment by andymckay** [comment]
Actually it might be worth having an add-on on this site that's signed and has an update URL to show how all that works.

**Comment by andymckay** [comment]
Forget my last two comments, I've got something working :)

**Comment by andymckay** [comment]
I would suggest once #305 lands, that we close this bug.
