### ISSUE TITLE
browser.devtools.panels.elements.createSidebarPane not working on Nightly

### ISSUE THREAD

**Issue by anant-svc** [mdn/webextensions-examples#366]
I've followed the documentation to create browser.devtools.panels.elements.createSidebarPane with setObject.
I want to set custom html element in my pane.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/ElementsPanel/createSidebarPane

Browser: Nightly 63.0a1 (2018-08-07) (32-bit)

Expected result:
- It should show pane with the JSON object defined

Actual result:
- It shows a blank screen pane.

**Comment by anant-svc** [comment]
Can you please provide more detail examples? so that many Firefox developers will get the benefit.

**Comment by wbamberg** [comment]
This tracker is for issues relating to the examples in this repo. For general developer support questions, please ask in https://discourse.mozilla.org/c/add-ons/development.

**Comment by anant-svc** [comment]
@wbamberg Thank for the reply, I post my question on: https://discourse.mozilla.org/c/add-ons/development
