### ISSUE TITLE
WebExtensions & Progressive Web Apps

### ISSUE THREAD

**Issue by ohenepee** [mdn/webextensions-examples#370]
I've sent the following message to the following Mozilla IRC channels `#mobile`, `#webextensions`, `#addons`... of course its either no response or no one know much about it and its been 24 hours already.

**Are WebExtensions loaded and reachable (communication) from PWAs in Firefox for Android?**

**Comment by wbamberg** [comment]
This tracker is for issues relating to the examples in this repo. For general developer support questions, please ask in https://discourse.mozilla.org/c/add-ons/development.
