### ISSUE TITLE
beastify displays nothing, but reset button works (resolved)

### ISSUE THREAD

**Issue by stephengarn** [mdn/webextensions-examples#375]
Clicked on Frog, whiteness (no image), clicked on Turtle, whiteness (no image). Click Reset, displays original content of URL.

**Comment by stephengarn** [comment]
Windows 10 Firework Quantum v 62

**Comment by irenesmith** [comment]
Thank you for reporting the problem. I won't have access to a Windows machine until next week, but I did try it on my Mac and it works as described. How did you install the extension? Did you edit the manifest in any way?

**Comment by stephengarn** [comment]
error on my end.

**Comment by irenesmith** [comment]
Thanks for letting us know. Glad it worked out for you.
