### ISSUE TITLE
Different version of an Example Extension

### ISSUE THREAD

**Issue by AP-LM** [mdn/webextensions-examples#388]
So, I was thinking of doing a different version of the Emoji map extension using idioms instead of emojis. Would that be a good idea?

**Comment by wbamberg** [comment]
Thanks for your interest in contributing!

I'm not really the maintainer of this repo any more, but IMO this isn't a very appropriate example. The point of these examples is to show how to use WebExtension APIs. The emoji map example is intended to demo how to use content scripts. If your version used the same WebExtension features, but just replaced different bits of the page, then it would really just duplicate the existing one.

If you're keen to contribute to this repo it might be better to choose an existing issue. These look like they might be promising:

* https://github.com/mdn/webextensions-examples/issues/359
* https://github.com/mdn/webextensions-examples/issues/356
* https://github.com/mdn/webextensions-examples/issues/346

**Comment by rebloor** [comment]
Unclear whether offered to contribute was fulfilled, closing is no further comment for five years
