### ISSUE TITLE
jpm run does not work

### ISSUE THREAD

**Issue by floriancastelain** [mdn/webextensions-examples#395]
Hello. (question asked here too: https://stackoverflow.com/questions/53998429/jpm-run-command-has-an-invalid-manifest)

When I run `jpm run -b "C:\Program Files\Firefox Developer Edition\firefox.exe"`,
the console gives me the following warnings:

> 1546371425561   addons.xpi-utils        WARN    addMetadata: Add-on
> @celestus-firefox-extension is invalid: Error: File
> C:\Users\user\AppData\Local\Temp\3f4ff82f-9dfc-4065-a6c7-7e9719d0c286\extensions\@celestus-firefox-extension.xpi
> does not contain a valid
> manifest(resource://gre/modules/addons/XPIInstall.jsm:557:11) JS Stack
> trace:
> 
> loadManifest@XPIInstall.jsm:557:11
> 
> 
> awaitPromise@XPIProvider.jsm:188:3
> 
> 
> syncLoadManifestFromFile@XPIInstall.jsm:620:10
> 
> 
> addMetadata@XPIDatabase.jsm:2334:21
> 
> 
> processFileChanges@XPIDatabase.jsm:2686:21
> 
> 
> checkForChanges@XPIProvider.jsm:2581:34
> 
> 
> startup@XPIProvider.jsm:2159:25
> 
> 
> callProvider@AddonManager.jsm:203:12
> 
> 
> _startProvider@AddonManager.jsm:652:5
> 
> 
> startup@AddonManager.jsm:805:9
> 
> startup@AddonManager.jsm:2775:5
> 
> observe@addonManager.js:66:9
> 
> 1546371425681   addons.webextension.screenshots@mozilla.org     WARN  
> Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid
> host permission: resource://pdf.js/
> 
> 1546371425681   addons.webextension.screenshots@mozilla.org     WARN  
> Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid
> host permission: about:reader*

Firefox opens as expected, but the icon that is supposed to be there is not there.
[![enter image description here][2]][2]

I can't find anything that could help me fix that. Some said it was because of a JSONwith an invalid format but everything is clear on my side.

Could anyone help me solve this problem?

edit: Just tried with a console with admin rights, does not change anything.

  [1]: https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tutorials/Getting_Started_(jpm)
  [2]: https://i.stack.imgur.com/2w789.png

**Comment by wbamberg** [comment]
Which version of Firefox are you running? As the [tutorial you linked](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tutorials/Getting_Started_(jpm)) says, jpm is not supported since Firefox 57. Please look at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions instead.

**Comment by floriancastelain** [comment]
Well, sometimes I need to read more carefully. I run developer edition 65.0b7. Sorry to disturb for such a newby mistake.

**Comment by wbamberg** [comment]
No problem @floriancastelain , glad I could help :).
