### ISSUE TITLE
Remove built extensions

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#397]
We have a directory (https://github.com/mdn/webextensions-examples/tree/master/build) of built and signed versions of the extensions in this repo, for people who don't want to use "temporary install".

This was created in https://github.com/mdn/webextensions-examples/pull/162. It was always going to be a pain to maintain and predictably, it has not been maintained, so I propose we remove the build directory.

**Comment by sneakypete81** [comment]
>  It was always going to be a pain to maintain

You're right, but perhaps another way could be to consider what can be done to make this painless. What can be done to help automate this?

Providing an example of how to implement a streamlined release process would be useful for add-on developers.

If something's painful, do it as much as possible :-)

**Comment by wbamberg** [comment]
This is a good idea, but this bug just reflects the current reality. If we haven't been able to maintain the current process properly, who is going to research and implement a system for automating the process?
