### ISSUE TITLE
All examples needs to be updated

### ISSUE THREAD

**Issue by JonasNo** [mdn/webextensions-examples#399]
All examples needs to be updated to work with the API changes and the new security added to Firefox.
Many of the examples are 2 years old for crying out loud!

**Comment by wbamberg** [comment]
If there are specific examples that need specific updates due to specific API changes, a bug report listing them would be helpful. But a bug saying "all examples need to be updated" is not helpful.

> Many of the examples are 2 years old for crying out loud!

Many APIs have also not been changed in that time, too.
