### ISSUE TITLE
How to set a width to the Bestify addon?

### ISSUE THREAD

**Issue by vhugogarcia** [mdn/webextensions-examples#4]
Hello friends,

I created my first web extension for Firefox and it worked just fine, however I'm wondering how can I define the width and height of the popup that appears when I click the icon in the toolbar?

any idea?

Thanks in advance

**Comment by wbamberg** [comment]
Hi

As far as I know this is not possible: the popup is automatically sized to fit its contents. It might be worth asking to see if this could be supported in a future version? You could try asking here: https://discourse.mozilla-community.org/c/add-ons.

Will
