### ISSUE TITLE
tabs-tabs-tabs needs a review

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#40]
https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs

**Comment by kmaglione** [comment]
```js
  function callOnActiveTab(callback) {
    chrome.tabs.query({active: true, currentWindow: true}, (tabs) => {
      tabs.forEach(callback);
    });
  }
```

Your click listener also needs an `e.preventDefault()`

Otherwise, looks good.

**Comment by lv7777** [comment]
I tried this extension.
I suggest add feature that  "move new window this tab" and "alert info this tab"

**Comment by wbamberg** [comment]
=> https://github.com/mdn/webextensions-examples/commit/8cce7fda06ac8d57bd09fe6caea150825d90dc63

**Comment by wbamberg** [comment]
> I suggest add feature that "move new window this tab" and "alert info this tab"

These are good suggestions, and I'd happily take PRs for them, but I'm not planning to add them myself right now.

**Comment by lv7777** [comment]
ok.
Actually, I implemented this feature for learning.
I may send pull request.
