### ISSUE TITLE
chill-out example has errors and will not load

### ISSUE THREAD

**Issue by rbhall52** [mdn/webextensions-examples#401]
When I tried to load chill-out into firefox and run it, the debugger said "There was an error during installation: JSON.parse: unexpected character at line 7 column 1 of the JSON data". I looked at the code but was not sure what the problem is, because it is all html code, which I have not worked with in a while. I am using firefox 64.0 64bit on a 64bit windows 7 home premium laptop.

**Comment by rebloor** [comment]
Tested on macOS and worked as expected
