### ISSUE TITLE
  ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by jestinjoy** [mdn/webextensions-examples#402]
Getting this when running the find-across-tabs extension. Occurred it on 60.4.0esr (64-bit) running on Debian

```
ReferenceError: browser is not defined[Learn More]
find.js:1:5
<anonymous>
file:///home/username/webextensions-examples-master/find-across-tabs/find.js:1:5
```

**Comment by rebloor** [comment]
Tested on macOS and works OK. Closing given no comment for four years
