### ISSUE TITLE
Update examples of manifest.json for compliance with Firefox 48+

### ISSUE THREAD

**Issue by GregDomjan** [mdn/webextensions-examples#406]
Had some confusion and couldn't find doc on Applications manifest entry any longer.

Post issue #47 mozilla specific entry `applications` got renamed to more generic `browser_specific_settings` including in part issue [#addons/61](https://github.com/mozilla/addons/issues/61)

Would be nice to update manifest.json with new key, especially in examples that require a min version after 48

https://wiki.mozilla.org/WebExtensions/Applications
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

**Comment by rebloor** [comment]
Confirmed that no manifest.json includes the key.
