### ISSUE TITLE
Update 'proxy-blocker' to use proxy.onRequest

### ISSUE THREAD

**Issue by mconca** [mdn/webextensions-examples#410]
Support for PAC-style proxy scripts is going away in Firefox 71 as proxy.register, proxy.unregister and proxy.onProxyError are removed (see [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1545811)).

The proxy-blocker example should be updated to no longer use the removed API, and instead use the recommended proxy.onRequest API.

**Comment by Rob--W** [comment]
This was fixed by https://github.com/mdn/webextensions-examples/pull/422
