### ISSUE TITLE
Where can I see console logs?

### ISSUE THREAD

**Issue by bozdoz** [mdn/webextensions-examples#421]
This might be a silly question, but in many examples there are console logs, and I can't see them in any tab, nor in my terminal, where I'm running `web-ext run`.  For example, the tabs tabs tabs example has console.logs when tabs are moved, but I can't see them in developer tools.  Where should I be seeing them?

**Comment by wbamberg** [comment]
It's not a silly question.

Where to look for console output depends on the context your extension's code is running in. For most bits of an extension - like background scripts, options pages, sidebars - you use [a special toolbox that you can open in about:debugging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging#Developer_tools_toolbox). For content scripts, console output goes to the normal console for web page that the script is running in.

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging for more on this.

**Comment by bozdoz** [comment]
Ah, this was interesting information, but I still could not see the logs.  I realized from the output in the terminal that I was, in fact, looking at the wrong console.  

`web-ext run` shows this:

> Use --verbose or open Tools > Web Developer > Browser Console to see logging

**Browser Console** is different than the **Web Console**.

Thanks for your help!
