### ISSUE TITLE
what is wong: even the "borderify" demo NOT working any more?

### ISSUE THREAD

**Issue by lianhub** [mdn/webextensions-examples#424]
My own Firefox extension is NOT working any more:
* I created my own extension **one/two years ago**!
* So it worked with old version Firefox (don't remember the exact version)!

But with current Firefox, I found:
* Even the simple demo "borderify" fails too!
* (There is no error; we just do NOT see the "boderfiy" effect at all)
* [(Your First Extension: borderify)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension)

What is wrong? (I am currently using Firefox 68.0.1)
Does Firefox change any policy?

**Comment by silvererudite** [comment]
I just followed the tutorial and it did work for me. would you show your manifest and js files?

**Comment by Rocketblaster247** [comment]
Same here, doesn't work at all.

**Comment by anknits** [comment]
@lianhub and @Rocketblaster247 Are you trying to observe the results in Private window? If so, it won't work. Try using the Inspect button, it will offer you insights as you try to use the extension

**Comment by CztNLv** [comment]
Maybe should check the file's name. It's "manifest.json", NOT "mainfest.json"

**Comment by EliRibble** [comment]
I just tried this. Borderify didn't work for me. Neither did my own extension. Turns out the reason was because I had set "Firefox will: Never remember history" in my Preferences. This makes Firefox constantly use private browsing windows, which by nature disable all add-ons. You need to turn off this setting to test add-ons.

**Comment by wingman-jr-addon** [comment]
Well now I'm curious. @lianhub @Rocketblaster247 Did the advice from @anknits or @EliRibble get it working for you?

**Comment by GhostDog98** [comment]
> My own Firefox extension is NOT working any more:
> 
>     * I created my own extension **one/two years ago**!
> 
>     * So it worked with old version Firefox (don't remember the exact version)!
> 
> 
> But with current Firefox, I found:
> 
>     * Even the simple demo "borderify" fails too!
> 
>     * (There is no error; we just do NOT see the "boderfiy" effect at all)
> 
>     * [(Your First Extension: borderify)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension)
> 
> 
> What is wrong? (I am currently using Firefox 68.0.1)
> Does Firefox change any policy?

Is there any chance you are using Ubuntu? I am getting a similar (but slightly different) problem...

**Comment by caitmuenster** [comment]
Thanks to @EliRibble for providing [this solution](https://github.com/mdn/webextensions-examples/issues/424#issuecomment-631125076). 

If there are any other questions, please raise them over on the [add-ons community forum](https://github.com/mdn/webextensions-examples/issues/424#issuecomment-631125076).

**Comment by Mykola-Veryha** [comment]
The problem is not solved
