### ISSUE TITLE
Borderify

### ISSUE THREAD

**Issue by esmaeelE** [mdn/webextensions-examples#429]
In borderify extension change  "matches": ["*://*.mozilla.org/*"] to  "matches": ["*://*mozilla.org/*"],
Remove dot (.) before mozilla that works for URLs haven't www. .

**Comment by junngo** [comment]
I think that mozilla url's doesn't be changed. And Borderify extension is working well.
In the chrome browser, address bar no longer show 'www' url.
If Borderify extension is not working or you have another question, Let me know.
