### ISSUE TITLE
windows.create() promise will never be fulfilled

### ISSUE THREAD

**Issue by mrsndmn** [mdn/webextensions-examples#431]
Snippet from this example:
https://github.com/mdn/webextensions-examples/blob/master/window-manipulator/window.js#L28
```js
let creating = browser.windows.create(createData);
  creating.then(() => {
  console.log("The normal window has been created");
});
```
I cant see `console.log`  message while i am inspecting this extension. 

I only see such messages:
```
Navigated to chrome://devtools/content/shared/webextension-fallback.html
Webconsole context has changed
```

It seems that this promise will never be fullfiled. Looks like a bug in WebExtensions API because [examples from MDN ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create) don't work too.

**Comment by chrisdavidmills** [comment]
@rebloor something else you could take a look at. Thanks!

**Comment by mrsndmn** [comment]
I also created [bugzilla report](https://bugzilla.mozilla.org/show_bug.cgi?id=1593504)

**Comment by rpl** [comment]
@rebloor I just closed [Bug 1593504](https://bugzilla.mozilla.org/show_bug.cgi?id=1593504) as invalid because this behavior is expected, but we should also fix the window-manipulator example accordingly, see:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1593504#c2
- https://bugzilla.mozilla.org/show_bug.cgi?id=1593504#c3

**Comment by mrsndmn** [comment]
I tested this extension with `sidebar_action` instead of `browser_action` and now it works.

**Comment by rebloor** [comment]
@chrisdavidmills WOW question, would you create a parallel issue for this in the sprints repo?

**Comment by chrisdavidmills** [comment]
@rebloor it's up to you really; I'm happy for you to do that if it makes things easier to keep track of.

**Comment by rebloor** [comment]
Thanks @chrisdavidmills, I'll probably go for duplicating as I would prefer to have a single definitive list.
