### ISSUE TITLE
Is there any example which shows how to get the current page URL and modify it?

### ISSUE THREAD

**Issue by parrotcar00** [mdn/webextensions-examples#433]
Wanted to write an extension which detects a certain url pattern and redirects the user to a different version of the website after finding a given URL pattern. Is there any example that shows how to get current URL and modify it or anything close to that?

**Comment by beverlyhillz** [comment]
var str= window.location.protocol + "//" + window.location.host + "/" + window.location.pathname + window.location.search;console.log(str);
    var exp=RegExp('https://*/*');
    if(exp.test(str))
      {
        location.replace('http://example.com');
      }

using this in content script of the extension will redirect you if the url matches the regular-expression.

Is this what you were looking for?
