### ISSUE TITLE
deal with all the chilloutandwatchsomecatgifs.com links

### ISSUE THREAD

**Issue by ChangePlaces** [mdn/webextensions-examples#436]
they're forwarded somewhere and my adblocker goes insane! obviously no cat gifs, but a sly way of good quality backlinks?

**Comment by wbamberg** [comment]
@rebloor , could you take a look at this please? I don't think we should be sending people here. But I don't know a truly reliable source of cat gifs.

**Comment by rebloor** [comment]
@wbamberg Yes it would seem that has chilloutandwatchsomecatgifs.com gone beyond chilled and checked out. What about https://giphy.com/explore/cat? It would seem unlikely that they're going to shut up shop and sell off to an ad host anytime soon.

**Comment by chrisdavidmills** [comment]
@rebloor LGTM.

**Comment by ChangePlaces** [comment]
https://www.topbestalternatives.com/lorempixel/

Lorempixel.com was the defacto placeholder image site, but it goes down a lot. Here are some alternatives. I have no idea about it, but there's placekitten.com

**Comment by rebloor** [comment]
@wbamberg see [PR #440](https://github.com/mdn/webextensions-examples/pull/440)

**Comment by wbamberg** [comment]
Thanks for taking care of this @rebloor .
