### ISSUE TITLE
Imagify not working due to deprecated extension.getURL

### ISSUE THREAD

**Issue by ManishAradwad** [mdn/webextensions-examples#448]
Imagify is not working due to deprecated `extension.getURL` in content.js 
It works properly when `runtime.getURL` is used.
I'll be sending a PR fixing this shortly

**Comment by rebloor** [comment]
@ManishAradwad I have merged your change, given that it's preferable we are using the non-deprecated API. However, I couldn't find an issue with the extension in Firefox 76, so I am curious, what issue did you observe?

**Comment by ManishAradwad** [comment]
When I tried dropping(or loading from my PC) an image in the sidebar nothing happened to the page. So I thought it was happening due to this api.
