### ISSUE TITLE
context-menu does not show in one example code, 1 example broken?

### ISSUE THREAD

**Issue by dimyme** [mdn/webextensions-examples#453]
https://github.com/mdn/webextensions-examples/tree/master/context-menu-copy-link-with-types

the context-menu does not show for me on x86 PC firefox. Just does not appear after I do in bash : 

`web-ext run`

the example is being referred to at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items
though the other example "menu-demo" from the above page works as advertised for me.

**Comment by corepiece** [comment]
Downloaded the directory, tested in Mozilla 99 (64-bit) as temporary extension: Does not work. No right-click menu is shown.

**Comment by corepiece** [comment]
Downloaded the directory, loaded it as "temporary extension" in Firefox 99 (64-bit): no menu shoes up/does not work.

**Comment by corepiece** [comment]
Can you help @yfdyh000 ?

**Comment by Rob--W** [comment]
When I load the extension with `web-ext run`, a menu item does appear (on Linux).

The linked screenshot is from the menu-demo example.
There is no screenshot for the [context-menu-copy-link-with-types](https://github.com/mdn/webextensions-examples/tree/master/context-menu-copy-link-with-types) demo, but it will appear if you right-clink on a link.

**Comment by rebloor** [comment]
Also ran and confirmed this works on a Mac, closing as there's been no further comments from reporter.
