### ISSUE TITLE
beastify does not work on android

### ISSUE THREAD

**Issue by adjenks** [mdn/webextensions-examples#454]
I installed the latest firefox nightly for android and just installed and ran the beastify example and it failed.
The error says that it says it needs host permissions. It shouldn't need this because it has "activeTab", so my guess is that when the popup opens, the popup becomes the active tab, so you no longer have permission for it. Unlike in the desktop browser the popup is full-screen, not a little dropdown, so it does at least feel like an active tab while it's open. Can anyone else verify this as a bug?

**Comment by adjenks** [comment]
Actually this is confirmed here:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups
>In Firefox Android 57, the popup is shown as a normal page in a new tab.
So, how would one call "executeScript()" from a popup using just the "activeTab" permission if the popup becomes the active tab...?

**Comment by adjenks** [comment]
I imagine I could do the following to work around it:

1. Have a background script running
2. Send a message from the popup script to the background script to trigger a function with a delay.
3. Call `window.close()` on the popup.
4. After a short delay in the background script execute the code that the popup script would have liked to execute, because the active tab is now the correct tab.

Might work... but in the meantime I'm just not going to use popups because this seems goofy.

**Comment by caitmuenster** [comment]
Firefox for Android currently only supports a limited number of Recommended Extensions.

**Comment by adjenks** [comment]
@caitmuenster What? It's a development app, I'm not installing it via the store I'm building it myself and loading it for testing. The problem was happening when I load it as a temporary add on.

**Comment by caitmuenster** [comment]
@adjenks Sorry for the confusion; Firefox for Android doesn't have all of the APIs that desktop has, and because it only supports a limited number of extensions on release, we're not planning to update the example in this repo to be compatible. 

However, I saw that you were interested in finding out if other people are experiencing some of the things you were seeing with the beastify test. You might want to share your thoughts on our [community forum](https://discourse.mozilla.org/c/add-ons/); more developers tend to visit and engage on the forum than they do on this repo. :)

**Comment by adjenks** [comment]
@caitmuenster Oh, thank you for the info and thank you for directing me to the forum. I don't think any of the APIs that this used were removed, so I think it should still be compatible with all the APIs in the new version.

**Comment by Rob--W** [comment]
The activeTab permission did not work as expected on the new Firefox for Android until version 87. When this issue was filed, the example didn't work, but nowadays it should.

The bug about implementing activeTab is at: https://bugzilla.mozilla.org/show_bug.cgi?id=1625593

**Comment by adjenks** [comment]
Thank you @Rob--W ! I appreciate finally receiving an answer. I haven't looked at this in a while but I was planning on picking it up again. I had a project based off of it and I needed to fix this before I could continue. Thanks!!!
