### ISSUE TITLE
Hooks to run before and after code reloading

### ISSUE THREAD

**Issue by ro6** [mdn/webextensions-examples#461]
I'm coming from the ClojureScript world where it's common to have functions you can run before and after loading new/updated code (e.g. to add/remove event listeners).

Can the same be done with `web-ext run` reloading?

**Comment by caitmuenster** [comment]
Hi @ro6, apologies for the late response. Other developers may be able to share their thoughts if you post this on the [add-ons community forum](https://discourse.mozilla.org/c/add-ons/development/).
