### ISSUE TITLE
Is native-messaging example broken?

### ISSUE THREAD

**Issue by DaniellMesquita** [mdn/webextensions-examples#467]
I'm on Linux, and I get this on console: "Attempt to postMessage on disconnected port"
Thread on Mozilla Forums: https://discourse.mozilla.org/t/nativemessaging-addon-with-nothing-in-the-browser-s-console/74740/9
Related issue: https://github.com/mdn/webextensions-examples/issues/266 by @zelad

**Comment by DaniellMesquita** [comment]
@eug48 

@e2e8, this example is since 2019 without updates.

**Comment by wbamberg** [comment]
@DaniellMesquita , I haven't been the maintainer of this repo for more than 2 years already. Sorry I can't help.

**Comment by chrisdavidmills** [comment]
@caitmuenster could one of your folks have a look at this one? Thanks!

**Comment by Rob--W** [comment]
Your code at https://github.com/Floflis/browsernewtab/blob/19688e39eca597e50e8b6319c9176b4ff5833926/root-in-progress/bin/flobrowser does not resemble the native-messaging example from this repository.

I've replied at https://discourse.mozilla.org/t/nativemessaging-addon-with-error-in-console-attempt-to-postmessage-on-disconnected-port/74740/13

**Comment by zombie** [comment]
@DaniellMesquita Please don't ping multiple people in your issues, either here or via discourse.

All open issues are looked at in time, please be respectful our time and attention.
