### ISSUE TITLE
Can I use FireFox Add-on content script to navigate some urls from one web page?

### ISSUE THREAD

**Issue by zydjohnHotmail** [mdn/webextensions-examples#468]
Hello:
I am now creating one FireFox add-on, which I need to use content script to navigate some web links from one main page.
For example, if I search for “FireFox Extension” inside Github home page, I can see this URL:
https://github.com/search?q=firefox+extension
There are 5000+ URLs returned from the search.
In my FireFox Add-on, I need to navigate to all the URLs in the first page, which is about 50 URLs.
What I want to do is: when content script navigate to each of the 50 URLs, I send the URL as a string message to background script, then background script save all 50 URLs into a local storage array.
I mean I want to use content script to automatically navigate to each of the URLs in one page, not click on each URL by hand.
Let me know if it is possible, if yes, share some code for content script.  If no, then let me know if there is any work around.
Thanks,

**Comment by samuelroland** [comment]
Hi @zydjohnHotmail
I think it is not the right place to get help for your extension (look at the readme under section "Problems?", --> you should repost on the discourse forum, maybe you will find some help), but to answer you (I never used content script actually): I don't really understand what you are trying to implement and how look like the result from a user point perspective. If you are trying to show more information in the list of URL after a search or to show a complete list of the 5000 URLs, I suggest you to use the [GitHub API](https://docs.github.com/en/rest/reference/search) instead of dealing with HTML.

**Comment by zydjohnHotmail** [comment]
Hello:
I don't know how to describe what I want to do.
Usually, when I write a Firefox Addon, I assume the user navigate to one specific web page, then the content script and/or background script can work to provide some functions.  
But when I am facing the issue is: if the user navigate to one specific web page, but under the same domain, there are many (100+) URLs, for each URL in this domain, I want to collect some http request headers via background script.
If for example, there are only 2 or 3 URLs under one specific web page, then user can navigate to each of them, then background can collect some http requests, it is not a big deal; but for so many URLs under on specific web page, to visit all the URLs seems to be impossible, so I want to know if I can use content script to visit each of the URL automatically, then background script can collect the necessary information.
My question is not actually related to GitHub or GitHub API, but for all the situations.
For example, if you visit amazon.com; then even under the same category of products, there are hundreds of web pages, each one has its own URL. So I want to know if I can use the content script to visit those hundreds of web page, and at the same time, background can collect the HTTP requests to make up the each page.

**Comment by Rob--W** [comment]
This is not a forum to request support with extension development, but an issue tracker to track bugs and improvements in the examples in the extension documentation.

That having said, you can use `browser.tabs.create` (from the background page) to create the tabs that you want. Or disable the popup blocker and use `window.open` from the content script.
