### ISSUE TITLE
Add browser_specific_settings to borderify and beastify

### ISSUE THREAD

**Issue by 89z** [mdn/webextensions-examples#473]
I reviewed "your first webextension" [1] and your second webextension [2], and I tried to create an extension for Firefox for Android.

After beating my head against a wall for longer than I care to admit, I finally figured out that for an extension to work with Firefox for Android, the manifest must include `browser_specific_settings` key. This was difficult to discover, as its not included in the manifest of either example.

1. <https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension>
2. <https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension>
3. <https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings>

**Comment by Rob--W** [comment]
How are you testing the add-on?
I followed the following steps and the add-on works as expected

1. Clone the repository - `git clone https://github.com/mdn/webextensions-examples`
2. Enter the [`beastify`](https://github.com/mdn/webextensions-examples/tree/master/beastify) directory - `cd beastify`
3. Get the android device ID via - `adb devices`
    (or run `web-ext` and see the device IDs printed in the error message: `web-ext run -t firefox-android`)
4. Run Firefox on my phone ([Firefox Nightly for Android](https://play.google.com/store/apps/details?id=org.mozilla.fenix) - `web-ext run -t firefox-android --android-device=DeviceIDfromStep3Here --firefox-apk=org.mozilla.fenix`
    (the `--firefox-apk` flag is optional, without it the "default" Firefox browser is launched if available).
5. [android] Click on Add-ons and confirm that the add-on is installed.
6. [android] Visit any web page (e.g. example.com) and click on the add-on button to confirm that the add-on turns the page in a picture.
7. Press Ctrl-C from the terminal, and the Firefox instance on the mobile will close.

I've tested with the most recent version of Firefox Nightly on Android and `web-ext 6.2.0`, using the stock example of the `beastify` example (which does not have the `browser_specific_settings` key).

What steps did you follow to get a different result?

**Comment by 89z** [comment]
> 3. Get the android device ID via - `adb devices`

You lost me here. Why do I need to do that? I just add `borderify` contents to Zip, rename to XPI, upload to GitHub, then click the XPI on my mobile browser.

**Comment by Rob--W** [comment]
> > 3. Get the android device ID via - `adb devices`
> 
> You lost me here. Why do I need to do that? I just add `borderify` contents to Zip, rename to XPI, upload to GitHub, then click the XPI on my mobile browser.

With `web-ext`, you'll be able to run, edit and debug your extension on your phone. By default it's not possible to install an extension that you create in this manner (even after renaming).

Could you explain which steps you've followed? Then I can try to improve documentation as needed based on your feedback/experience.

I think that we can already try to emphasize that an ID is needed at https://extensionworkshop.com/documentation/publish/package-your-extension/

**Comment by 89z** [comment]
> With `web-ext`, you'll be able to run, edit and debug your extension on your phone. By default it's not possible to install an extension that you create in this manner (even after renaming).

I dont use `web-ext`, which I guess is good, because it seems like youre saying that you cant even install add-ons created from that tool anyway?

> Could you explain which steps you've followed? Then I can try to improve documentation as needed based on your feedback/experience.

I think I made it pretty clear already. Quoting myself:

> I just add `borderify` contents to Zip, rename to XPI, upload to GitHub, then click the XPI on my mobile browser.

> I think that we can already try to emphasize that an ID is needed at https://extensionworkshop.com/documentation/publish/package-your-extension/

I dont use that domain at all. I use this:

https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions

**Comment by Rob--W** [comment]
> > With `web-ext`, you'll be able to run, edit and debug your extension on your phone. By default it's not possible to install an extension that you create in this manner (even after renaming).
> 
> I dont use `web-ext`, which I guess is good, because it seems like youre saying that you cant even install add-ons created from that tool anyway?

The tool automatically runs the add-on in the mobile browser. You can edit the source, save it, and the tool automatically reloads the add-on.

> > Could you explain which steps you've followed? Then I can try to improve documentation as needed based on your feedback/experience.
> 
> I think I made it pretty clear already. Quoting myself:
> 
> > I just add `borderify` contents to Zip, rename to XPI, upload to GitHub, then click the XPI on my mobile browser.

Can you link to the page that made you think that the add-on would work in this way? I really want to improve the documentation where possible.

> > I think that we can already try to emphasize that an ID is needed at https://extensionworkshop.com/documentation/publish/package-your-extension/
> 
> I dont use that domain at all. I use this:
> 
> https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions

The extensionworkshop domain is where most Firefox-specific extension documentation moved to. API references are still on MDN, but Firefox-specific docs are on the extensionworkshop site. Several pages on MDN redirect or link to the extension workshop site.

**Comment by 89z** [comment]
> The tool automatically runs the add-on in the mobile browser. You can edit the source, save it, and the tool automatically reloads the add-on.

Thats nice, but I dont really care about that. I care about getting the add-on to work in the first place, which was an issue because of `brower_specific_settings`, not because of any tool.

> Can you link to the page that made you think that the add-on would work in this way? I really want to improve the documentation where possible.

It does work that way. Ive already used the process several times today, and it works just fine. Here is my add-on if you want to test:

https://github.com/89z/rosso/releases

> The extensionworkshop domain is where most Firefox-specific extension documentation moved to. API references are still on MDN, but Firefox-specific docs are on the extensionworkshop site. Several pages on MDN redirect or link to the extension workshop site.

From this page:

https://github.com/mdn/webextensions-examples

you see clearly that this is linked:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions

If you want people to start using a different domain, you should start with your own repo.

**Comment by Rob--W** [comment]
> because of `brower_specific_settings`, not because of any tool.
> 
> > Can you link to the page that made you think that the add-on would work in this way? I really want to improve the documentation where possible.
> 
> It does work that way. Ive already used the process several times today, and it works just fine. Here is my add-on if you want to test:
> 
> https://github.com/89z/rosso/releases

I know that the key is required when you zip the directory and rename it to a xpi file. This is however not a way to get an add-on package that works for everyone. The default behavior is that users get a message that the add-on is corrupt. If you got different results, then that's due to some special steps on your end.

> > The extensionworkshop domain is where most Firefox-specific extension documentation moved to. API references are still on MDN, but Firefox-specific docs are on the extensionworkshop site. Several pages on MDN redirect or link to the extension workshop site.
> 
> From this page:
> 
> https://github.com/mdn/webextensions-examples
> 
> you see clearly that this is linked:
> 
> https://developer.mozilla.org/en-US/Add-ons/WebExtensions
> 
> If you want people to start using a different domain, you should start with your own repo.

I mentioned the domain/page because I thought that you might have gotten the instructions from there. I have no particular interest in one domain over another. The README that you linked provided instructions for using the examples on desktop Firefox. And they do indeed work on desktop. There are no specific instructions for Firefox on Android here, but you still managed to get something in the end.

You opened an issue here to claim that the browser_specific_settings key is missing, motivated by your experience on Android. This key is not missing from the example, but it is needed for the specific (and unsupported) distribution method that you are using. Without knowing how you got to these steps I cannot improve the documentation.

**Comment by 89z** [comment]
> I know that the key is required when you zip the directory and rename it to a xpi file.

Its required for Android Firefox, full stop, as detailed here:

<https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings>

> This is however not a way to get an add-on package that works for everyone. The default behavior is that users get a message that the add-on is corrupt. If you got different results, then that's due to some special steps on your end.

I was getting a corrupt message, but once I added `browser_specific_settings`, it works fine.

> You opened an issue here to claim that the `browser_specific_settings` key is missing, motivated by your experience on Android. This key is not missing from the example

Yeah, it is:

- https://github.com/mdn/webextensions-examples/blob/master/beastify/manifest.json
- https://github.com/mdn/webextensions-examples/blob/master/borderify/manifest.json

> but it is needed for the specific (and unsupported) distribution method that you are using. Without knowing how you got to these steps I cannot improve the documentation.

You keep asking for this, and I keep telling you the same answer:

> I just add `borderify` contents to Zip, rename to XPI, upload to GitHub, then click the XPI on my mobile browser.

**Comment by 89z** [comment]
> Only if packaged as an unsigned xpi, but that's not unique to Android.

So what? People are allowed to use unsigned XPI. And when they do, they should know that `browser_specific_settings` is required. This documentation shouldnt only be for people using signed XPI.

> That it works after adding the key is NOT because of anything special with Android

It very much is because of Android, as detailed here:

<https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings>

> it's because of the way that you created the package. The steps that you are using are NOT the steps documented in this repository. This is the reason why the example does not work out of the box.

The reason the example doesnt work out of the box, it because it doesnt have the `browser_specific_settings` key, and it doesnt detail that its needed (at least not prominently enough).

> ... and who told you to do this? Where can I find the text/documentation that states that this would be a valid way to install an add-on on Firefox for Android?

I think this is the root of your misunderstanding. **What Ive done doesnt need to be documented to be a valid installation method**. If it works, its valid, by definition. Ideally all valid methods would be documented, but it seems by your commented that my method is not documented. Regardless, if my method is able to successfully install and produce a working add-on for me on Firefox Android, then **its a valid method**.

> You've filed an issue about the documentation. There is nothing wrong with the code (browser_specific_settings is NOT required but optional), there is something wrong with your packaging method.

Your logic is "because my method might not be documented", that is not valid. First, I am not conceding that is even true, but I am under no obligation to prove that my method is documented. Regardless, it seems to be found here:

https://extensionworkshop.com/documentation/publish/package-your-extension

Next, `browser_specific_settings` is required in some cases, as Ive said repeatedly, and shown evidence of, and shown references of. I dont think it would hurt to add it to `borderify` and `beastify`, but if people find that distasteful, as least it could be more prominently documented.

**Comment by Rob--W** [comment]
I've submitted two PRs to improve the documentation on MDN and the Extension Workshop sites:
- https://github.com/mdn/content/pull/8024
- https://github.com/mozilla/extension-workshop/pull/1078

> > That it works after adding the key is NOT because of anything special with Android
> 
> It very much is because of Android, as detailed here:
> 
> https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings

I have repeatedly told you that this is not an Android-specific thing. The documentation updates that I submitted describe the requirements in a more precise way.

> > ... and who told you to do this? Where can I find the text/documentation that states that this would be a valid way to install an add-on on Firefox for Android?
> 
> I think this is the root of your misunderstanding. **What Ive done doesnt need to be documented to be a valid installation method**. If it works, its valid, by definition. Ideally all valid methods would be documented, but it seems by your comments that my method is not documented. Regardless, if my method is able to successfully install and produce a working add-on for me on Firefox Android, then **its a valid method**.

There is no misunderstanding. I know how one can install such extensions, and that with that chosen approach an ID is required. Incidentally, although you've never replied with a full description of your installation method, [the notes in your repository](https://github.com/89z/rosso/tree/1.2.0#notes) confirms my suspicions of the installation method that you're using.


> > You've filed an issue about the documentation. There is nothing wrong with the code (browser_specific_settings is NOT required but optional), there is something wrong with your packaging method.
> 
> Your logic is "because my method might not be documented", that its not valid. First, I am not conceding that is even true, but I am under no obligation to prove that my method is documented.

You are asking for documentation updates, and asserting that the examples don't work. I showed a counterexample to disprove your claim; the extensions work for the installation mechanisms described/linked from this repo and MDN. Therefore the reported issue is invalid.
I was willing to correct documentation if needed (e.g. if you read those incomplete instructions in an official documentation page), but you're not being quite cooperative here...


> Regardless, it seems to be found here:
> 
> https://extensionworkshop.com/documentation/publish/package-your-extension

This is not the installation method that you're using. This describes how an extension can be zipped, e.g. to load it in `about:debugging` or to submit it for signing to AMO .

The closest description of the installation method that you're using is described for the old Firefox for Android browser (Fennec), at https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android-fennec/#install-and-run-your-extension-in-firefox-for-android . And as you can see there, the requirement of "browser_specific_settings" is clearly documented there.
