### ISSUE TITLE
None of the examples work for me. 

### ISSUE THREAD

**Issue by GhostDog98** [mdn/webextensions-examples#475]
Firefox Version: 91.0.1
OS: Ubuntu 20.04
If I attempt to load ANY unpacked extension, then it does not work. I can verify this by looking in the "debugging" page:
```
Error: Can't find profile directory.                                      XULStore.jsm:66:15
    load resource://gre/modules/XULStore.jsm:66
    XULStore resource://gre/modules/XULStore.jsm:24
```
I have checked all threads i can find about this and tried every fix. 
So far I've tried:
- Enabling History
- Checking for updates
- Enabling Cookies
- Allowing in all windows (including private, although I'm testing on non-private windows)
This happens with all 3 examples I've tried so far...

**Comment by Rob--W** [comment]
Could you share the full output of `about:support`? Are you able to install or use any add-on at all?

**Comment by GhostDog98** [comment]
Hi, it seems that for some reason re-installing fixed the issue, sorry for the inconvenience.
