### ISSUE TITLE
move and duplicate functionality not working as expected

### ISSUE THREAD

**Issue by khanstark** [mdn/webextensions-examples#48]
from the popup html,  'Move active tab' does not work properly...
`chrome.tabs.move([tab.id], {index: 0})` might not be responding 
remove and reload works perfectly fine.

**Comment by wbamberg** [comment]
Thanks for reporting this. Which version of Firefox are you using?

I think tabs.move() is only supported from Firefox 46, and tabs.duplicate() from Firefox 47. You should be able to check this using the "Browser Compatibility" section of the API reference docs:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Tabs/move#Browser_compatibility
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Tabs/duplicate#Browser_compatibility

As such, this add-on is only fully functional on Firefox 47 and up (and it works fine for me on Firefox 47, and fails as expected on Firefox 45). 

A way to check this for an add-on is using the "strict_min_version" key in the add-on's manifest.json: https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json. In fact, I thought that this should have prevented the add-on from installing in earlier versions but it seems like it doesn't. I think this might be a bug.

So, please let me know if it works in Firefox 47. If so, I'll close this (and maybe file another bug about strict_min_version).

**Comment by khanstark** [comment]
I was using firefox 45.0.1 while testing this add-on. But I have updated to 47 now, and yeah 'strict_min_version' needs to rectified because it didn't prevent installation on earlier versions, as obvious.

**Comment by khanstark** [comment]
It works fine in 47, but you need to look at the above issue of 'strict_min_version'.

**Comment by wbamberg** [comment]
'strict_min_version' is respected in FIrefox 47 and above: https://bugzilla.mozilla.org/show_bug.cgi?id=1192437.
