### ISSUE TITLE
 TypeError: browser.webNavigation is undefined

### ISSUE THREAD

**Issue by elnath78** [mdn/webextensions-examples#487]
I get this error when running the following code:

```
const filter = {
  url:
  [
    {pathEquals: "https://cp.creoweb.com/data/"}    
  ]
}

try { browser.webNavigation.onCompleted.addListener(navToPostPages, filter) }

catch(error){
    console.log (error.message);
}
```

Stuck here by days now. Differently, the `browser.runtime.sendMessage` in another part is working perfectly.

**Comment by Rob--W** [comment]
Your extension needs to declare the `webNavigation` permission in your manifest.json file.

P.S. I don't see how this issue relates to this repository.
