### ISSUE TITLE
Favourite Color bug manifest

### ISSUE THREAD

**Issue by badonyt** [mdn/webextensions-examples#498]
Hello, in the example FAVOURITE-COLOUR, i keep getting a bug which says **"Uncaught (in promise) Error: Managed storage manifest not found"**.

![image](https://user-images.githubusercontent.com/78484256/188191168-fc5675ae-ef7c-406e-9eef-74886468388f.png)

Its about the **storage** manifest, even doe its there.

Note:
Im using the **addon** in **debug mode**.

Thanks!

**Comment by rebloor** [comment]
@badonyt did you copy the content for the `favourite-colour-examples@mozilla.org.json` file from [Provisioning managed storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed#provisioning_managed_storage) rather than the readme for the example? The example for the file in Provisioning managed storage uses American English rather than British English. Using this copy I found the same error but changing to the version in the example readme fix the issue, and it worked as expected.

**Comment by Rob--W** [comment]
The (unexpected?) error was encountered before in https://bugzilla.mozilla.org/show_bug.cgi?id=1784446

The discussion there may help with identifying and resolving the problem.

@rebloor 
I think that we can improve the documentation; I'll talk with my team next week to determine the desired course of action, and add dev-doc-needed if needed.

**Comment by badonyt** [comment]
What do you mean @rebloor

**Comment by rebloor** [comment]
@badonyt I got the same error as you when I created the manage storage file based on [Provisioning managed storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed#provisioning_managed_storage) that is:
```
{
  "name": "favorite-color-examples@mozilla.org",
  "description": "ignored",
  "type": "storage",
  "data":
  {
    "color": "management thinks it should be blue!"
  }
}
```
However, using the file content in the example's readme description, that is:
```
{
  "name":  "favourite-colour-examples@mozilla.org",
  "description": "ignored",
  "type": "storage",
  "data": {
    "colour": "management thinks it should be blue!"
  }
}
```
The extension worked as expected.

**Comment by badonyt** [comment]
i still havent understood how to use the storage permission

**Comment by rebloor** [comment]
@badonyt do you mean the "storage permission" or "storage manifest"? Your reported problem appears to be with the storage manifest. If you still can't get the example to run, could you add screenshots showing the location you stored the `favourite-colour-examples@mozilla.org.json` file in and a copy of its content? If, however, you need more advice on using "storage permission" try posting a question on the [Add-ons forum](https://discourse.mozilla.org/c/add-ons).

**Comment by badonyt** [comment]
i dont know where to put this: `{
  "name":  "favourite-colour-examples@mozilla.org",
  "description": "ignored",
  "type": "storage",
  "data": {
    "colour": "management thinks it should be blue!"
  }
}`

**Comment by rebloor** [comment]
Are you on Mac, Linux, or PC?

**Comment by badonyt** [comment]
PC, WINDOWS 10, sorry for late response

**Comment by rebloor** [comment]
I don't have a Windows 10 machine to check but according to the documentation you should create a registry key with the following name:

`HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\ManagedStorage\<name>` – with <name> as `favourite-colour-examples@mozilla.org`.

The key should have a single default value, which is the path to the manifest.

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#windows

**Comment by rebloor** [comment]
Closing, as this doesn't appear to be an issue with the extension example
