### ISSUE TITLE
Native messaging example doesn't pong after a while

### ISSUE THREAD

**Issue by Risto-Stevcev** [mdn/webextensions-examples#499]
Here's a screencast of what it looks like:

![bug](https://user-images.githubusercontent.com/6767374/189088977-094bbadd-097e-4710-be21-279b762127af.gif)

**Comment by guest271314** [comment]
Is the beahaviour specific to Firefox?

**Comment by Risto-Stevcev** [comment]
I'm not sure, but it's happening on Firefox, I don't currently use Chrome or Safari

**Comment by guest271314** [comment]
Cannot reproduce.

I included this at the top of background.js

```
const start = new Date();
```

then this inside `onMessage` handler

```
console.log("Received: " + response, (new Date() - start) / 60000);
```

At the time of the screenshot of inspected window the extension has been active for 13 minutes.

![Screenshot_2022-12-11_07-21-21](https://user-images.githubusercontent.com/4174848/206912376-ae433720-f825-440b-95d9-ee335d499f64.png)
