### ISSUE TITLE
page-to-extension-messaging works on Firefox OS, after explicitely enabling it in Settings

### ISSUE THREAD

**Issue by anaran** [mdn/webextensions-examples#5]
So this is more a report it actually works, disguised as a minor issue that on Firefox OS people might think it does not work at first.

After installing the add-on on a firefox os device from a git working directory via WebIDE one has to go into the `Settings`->`Add-ons` panel and set it to `Enabled`.

It's great to have these examples. Thanks, Will!

**Comment by wbamberg** [comment]
I'm closing this, because it's not an issue with the repo, as far as I can tell.
