### ISSUE TITLE
Beastify doesn't pass validator on addons.mozilla.org

### ISSUE THREAD

**Issue by thePaulV** [mdn/webextensions-examples#50]
Attempting to get the Beastify example signed on AMO results in a validation error.

Steps to reproduce:

1. Check out examples
2. Edit manifest.json to have a unique id
3. Create XPI ([using these steps](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Packaging_and_Installation))

    `zip -r ../my-addon.xpi *`

4. Upload to [AMO](https://addons.mozilla.org/en-US/developers/addon/submit/2)

Expected:
1. Validation succeeds
2. If "Do not list my add-on on this site (beta)" is checked, should be possible to download a signed version

What happens:
1. Your add-on failed validation with 1 error. Invalid minimum version number
2. Impossible to proceed to next steps

Screenshot:
![screen shot 2016-03-29 at 9 10 14 pm](https://cloud.githubusercontent.com/assets/55456/14163563/b5ff44a4-f6c4-11e5-81d4-100a2c7898ab.png)

**Comment by wbamberg** [comment]
@thePaulV , could you please try changing the "strict_min_version" key in manifest.json to "45.0", and see if that fixes your problem?

It seems that 45.0.0 is not valid: https://addons.mozilla.org/en-US/firefox/pages/appversions/.

**Comment by thePaulV** [comment]
@wbamberg Success, changing strict_min_version to "45.0" results in an XPI that passes AMO validation.

**Comment by wbamberg** [comment]
@thePaulV , hopefully this should fix things: https://github.com/mdn/webextensions-examples/commit/4c567ae94557270c32980c10b37e63fb797098b0.
