### ISSUE TITLE
browser is not defined in firefox

### ISSUE THREAD

**Issue by dumpster-of-things** [mdn/webextensions-examples#504]
# https://github.com/mdn/webextensions-examples/issues/194
I have read discussion at the referenced issue, which has been marked "closed."
I do not see a solution for, nor explanation of why `browser` is undefined **in firefox**.

I am on version: `106.0.5 (64-bit) (Mozilla Firefox Snap for Ubuntu canonical-002 - 1.0)`

My goal is to get a list of urls for open tabs.
I am following along with examples on MDN, running code verbatim in devtools>console.
The various related examples all use methods of the `browser.tab` construct.
There does not seem to be any documentation for `broswer` on MDN and so I am opening this issue.

I'm new to web development, but not to programming/scripting; and so
 on the one hand: I'm probably missing something relatively pedestrian,
 on the other hand: This seems like something too fundamental to not be documented;
and so perhaps this is an opportunity to make said documentation more complete.

**Comment by Rob--W** [comment]
The tabs documentation ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs ) is part of the documentation of APIs for WebExtensions. That includes tutorials to run extension code

Are you able to find answers to your questions at:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions

**Comment by dumpster-of-things** [comment]
So I will need to author and publish a browser extension?  Is there not a built-in way to get a list of open urls (tabs) ?

**Comment by dumpster-of-things** [comment]
Also, to answer your question more directly:  no, I am not able to find my answer at the link you posted.  I'm looking for documentation for `broswer`.

**Comment by rebloor** [comment]
@dumpster-of-things I suspect your problem is that you need [Toolbox](https://extensionworkshop.com/documentation/develop/debugging/#developer-tools-toolbox) for browser to be defined when you run snippets in the console. To do this, open about:debugging then This Firefox, click Inspect against any installed or temporary extension, and open Console. You can then paste and run the example code in the console.
