### ISSUE TITLE
Build out .xpi's of the example add-ons

### ISSUE THREAD

**Issue by andymckay** [mdn/webextensions-examples#51]
So that users of Android can give them a try. We'll:
- sign them against AMO
- add them to github
- link them up somewhere
  ... script this so each time an add-on updates, we'll update this process.

**Comment by andymckay** [comment]
Actually @kumar303 don't you have a bug for this like this for mozilla/web-ext? Would be a nice test of it :smiley:

**Comment by kumar303** [comment]
I don't have a bug filed. Do you want to assign this to me?

**Comment by andymckay** [comment]
I can't, its in mdn, I don't have write access. @wbamberg would have to do that.

**Comment by kumar303** [comment]
We'll probably want to fix https://github.com/mozilla/web-ext/issues/198 for at least one of the examples

**Comment by wbamberg** [comment]
@kumar303 , do you need me to assign this to you, or can you just make a PR for it?

**Comment by kumar303** [comment]
If you can assign it to me it would be helpful just so I can track it along with everything else in my 'assigned' queue. I hope to make time for it soon.

**Comment by andymckay** [comment]
I think I'll just do this, sign them all as unlisted through AMO and add them to a build folder manually.

Anyone else contributing to this repo can then get added as an author on AMO.

**Comment by andymckay** [comment]
Signing only worked for 5 of the add-ons, the rest failed because other users have already registered them. I suggest we wait for #71 (and the web-ext change to land). The we can give them all a simple unique id that won't conflict with whats up there. I'll get to this in a week or two when I get back from PTO.

@wbamberg could you assign to me please?

**Comment by wbamberg** [comment]
It seems like I need to make you a collaborator in order to assign to you, so I've invited you to do that.

**Comment by kumar303** [comment]
Also, you could change the manifest IDs which will let you take ownership.

**Comment by wbamberg** [comment]
I think you did this, didn't you, @andymckay ?

**Comment by andymckay** [comment]
I did.

**Comment by andymckay** [comment]
But I haven't linked them up somewhere, any ideas where we could do that?

**Comment by wbamberg** [comment]
I've now mentioned it here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples, do you think that covers it?

**Comment by andymckay** [comment]
I wouldn't mind having links people could click on just to test them out, but at the same time I don't want to maintain that page on MDN. So sure let's do that, thanks @wbamberg
