### ISSUE TITLE
Image is not loading by innerHTML in the content-script-register

### ISSUE THREAD

**Issue by bhargavmungara** [mdn/webextensions-examples#514]
### What information was incorrect, unhelpful, or incomplete?

const defaultCode = "document.body.innerHTML = '<h1>This page has been eaten<h1>'";

This line is working but i am curious about when i add an image tag, it says the image is not loaded. 

Here's the screenshot 

<img width="1312" alt="Screenshot 2023-01-26 at 1 06 34 PM" src="https://user-images.githubusercontent.com/59245935/214781664-42201acd-a122-4f88-8470-08eb15a1b3cf.png">

Why the image is not loading even though it's valid syntax and valid HTML element

### What did you expect to see?

The image to load on the page with this line

const defaultCode = "document.body.innerHTML= '<img src=../ar.jpg />'";

**Comment by Rob--W** [comment]
The relation between this issue and the [content-scripts-register](https://github.com/mdn/webextensions-examples/tree/main/content-script-register) example is unclear.

You can look at the Network tab of your browser's Developer tools to see what imagine it is trying to load. Probably an image relative to the current document's URL. If you want to load a resource within your extension, declare the image file in your the `web_accessible_resources` section of your manifest.json file, and use `browser.runtime.getURL` to get the absolute URL to the image within the extension.

**Comment by bhargavmungara** [comment]
Will try
