### ISSUE TITLE
Please add example for "Paste text from clipboard"

### ISSUE THREAD

**Issue by Hellboy00000** [mdn/webextensions-examples#521]
This is in a background.js

This code can be used to create the example:

browser.menus.create({
    id: "whatever",
    title: "Paste clipboard Text"
});

browser.menus.onClicked.addListener((info, tab) => {
    navigator.clipboard.writeText("Paste Hello");   // This add the code to the clipboard
    // The code needed to paste the text
});

The context menu is not needed for the "paste code" i want to see, but i think that with this example is more easy for everyone to understand the code.

Thanks

**Comment by rebloor** [comment]
Is there not sufficient information for this in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#using_execcommand_2 ?

**Comment by Hellboy00000** [comment]
I try that but that example is using HTML (where it looks for a ID of the text area) and i don't use any HTML. I just want to "paste" in a web page in a browser using the extension. 

When i use that code say execCommand is deprecated.

**Comment by Rob--W** [comment]
The question you're asking and the code snippet are two different things.

"Paste" means reading from the clipboard.
The `writeText` call in the snippet writes to the clipboard, that's called "Copy".

What do you want that is not already covered in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard ?

**Comment by Hellboy00000** [comment]
I try that but that example use HTML to look for the ID of the text area were the text is going to be pasted. I really don't know how to do it. So if someone can share a example preferably with code i first share i am going to be really grateful.

**Comment by rebloor** [comment]
@Rob--W I think that @Hellboy00000 is looking for code to allow his extension to paste into a webpage. My understanding is you can't do that in code, the user has to initiate the paste. All the code can do is add or remove content from the clipboard.
