### ISSUE TITLE
Broken root-cert-stats due to var -> let change

### ISSUE THREAD

**Issue by MabryTyson** [mdn/webextensions-examples#536]
### What information was incorrect, unhelpful, or incomplete?

The current root-cert-stats extension throws a "TypeError: can't convert undefined to object" at popup.js 8:22
The popup window always shows "No data to display yet"

About a year ago, someone changed var to let at line 3 of background.js for the variable rootCertStats.  As a result, backgroundWindow.rootCertStats is undefined.

Changing the let back to var makes things work again.

### What did you expect to see?

No error should be thrown.  The popup window should show the stats.

### Do you have anything more you want to share?

It appears the var -> let change was done without testing.  I wonder how many other extensions were broken.

**Comment by rebloor** [comment]
@Rob--W I'll take a look at that

**Comment by rebloor** [comment]
Tested and found the following:

Checked, tested, and OK

1. annotate-page 
2. apply-css 
3. bookmark-it
4. chill-out
5. content-script-register
6. contextual-identities
7. cookie-bg-picker
8. dynamic-theme
9. eslint-example (only checked the extension)
10. export-helpers
11. favourite-colour – code looks OK however, unable to make work as expected will investigate further separately.
12. forget-it
13. history-deleter
14. latest-download
15. list-cookies
16. menu-accesskey-visible (doesn't seem to behave as expected, but unrelated to change – change reverted and retested – will investigate further separately)
18. menu-demo
19. mocha-client-tests/addon
20. native-messaging (doesn't seem to behave as expected, but unrelated to change  – change reverted and retested – will investigate further separately)
21. navigation-stats
22. notify-link-clicks-i18n
23. page-to-extension-messaging
24. quicknote
25. menu-remove-element (doesn't seem to behave as expected, but unrelated to change  – change reverted and retested – will investigate further separately)
26. selection-to-clipboard
27. stored-credentials
28. tabs-tabs-tabs
29. theme-switcher
30. top-sites
31. user-agent-rewriter
32. webpack-modules/addon
33. window-manipulator

Checked issues found and confirmed with test:

1. root-cert-stats – confirmed error and the change from let to var the fixes

**Comment by rebloor** [comment]
@Rob--W I've completed a review of the changed files. The only one that has the issue appears to be root-cert-stats. Would you like me to revert the change or should we do something else?
I did find fourextension that I couldn't get to work as expected, but I reverted the change and confirmed that made no difference:

- favourite-colour – which error when trying to read the file from managed storage
- menu-accesskey-visible - the access key did not work
- native-messaging - failed to get the "pong" with message that the port was closed
- menu-remove-element - the panel doesn't display.

I'll review these further later.

**Comment by Rob--W** [comment]
> @Rob--W I've completed a review of the changed files. The only one that has the issue appears to be root-cert-stats. Would you like me to revert the change or should we do something else?

Yes please revert to var. And prepend a comment that it's referenced from popup.js.

Ideally the example wouldn't use getBackgroundPage(), but instead use runtime.sendMessage from popup.js + runtime.onMessage in the background page to send the data back. It's bad practice to use getBackgroundPage(), e.g. in a private browsing window that logic breaks. If you can fix the example to use what I just described, it would be great.


> I did find fourextension that I couldn't get to work as expected, but I reverted the change and confirmed that made no difference:
> 
> - menu-accesskey-visible - the access key did not work
> - native-messaging - failed to get the "pong" with message that the port was closed
> - menu-remove-element - the panel doesn't display.

I confirmed by code review that these aren't affected by the var/let change.
