### ISSUE TITLE
Update root-cert-stats to use runtime.sendMessage

### ISSUE THREAD

**Issue by rebloor** [mdn/webextensions-examples#542]
### What information was incorrect, unhelpful, or incomplete?

This example use getBackgroundPage(). It's bad practice to use getBackgroundPage(), e.g. in a private browsing window that logic breaks. If you can fix the example to use what I just described, it would be great.

### What did you expect to see?

This example should use runtime.sendMessage from popup.js + runtime.onMessage in the background page to send the data back. 

### Do you have any supporting links, references, or citations?

See https://github.com/mdn/webextensions-examples/issues/536#issuecomment-1741871260

**Comment by ibzimh** [comment]
can i be assigned to this?

**Comment by ibzimh** [comment]
I've submitted a PR for this #547
