### ISSUE TITLE
tabs-tabs-tabs & favourite-colour

### ISSUE THREAD

**Issue by ind4rk** [mdn/webextensions-examples#55]
Hi, tabs-tabs-tabs & favourite-colour dont work for me. Tested in firefox 45 linux and windows.
tabs-tabs-tabs: 
->"Move active tab to the beginning of the window"
->"Move active tab to the end of the window"
->"Duplicate active tab"

On chrome runs

**Comment by wbamberg** [comment]
Those add-ons require Firefox 47 (currently Developer Edition) or later. You can check the minimum version required for each example by looking at the "strict_min_version" manifest key:

https://github.com/mdn/webextensions-examples/blob/master/favourite-colour/manifest.json#L5
https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json#L5

If you could confirm that these examples work for you with Firefox 47, that would be great, and I'll close this bug.

**Comment by ind4rk** [comment]
ok, sorry. I am newby.
on 47.0a2 (2016-04-25) linux ubuntu
tabs-tabs-tabs works but favourite-colour dont work.
"# Favourite Colour

Shows and stores your favourite colour, in storage.local
in the about:addons page for the add-on."
in about:addons page there are nothing to do.

**Comment by wbamberg** [comment]
Don't be sorry :). Minimum version requirements should be more obvious than they are. Firefox should refuse to install add-ons that don't meet the minimum version, and newer versions of Firefox do this, but Firefox 45 doesn't have that fix.

>  in about:addons page there are nothing to do.

To be clear: in about:addons you should see a button labelled "Preferences" next to the add-on, like: https://i.imgur.com/yRJQ5Vj.png. If you click the button, you should see the options UI: https://i.imgur.com/HALMbzY.png.

Are you seeing any of that?

**Comment by ind4rk** [comment]
Firefox version [http://i.imgur.com/5GGsQkK.png](http://i.imgur.com/5GGsQkK.png) 
about:addons page for the add-on [http://i.imgur.com/QKPUzxy.png](http://i.imgur.com/QKPUzxy.png)
about:addons [http://i.imgur.com/remjDjW.png](http://i.imgur.com/remjDjW.png)
I test on windows 7 and same result :(

**Comment by wbamberg** [comment]
Sorry, could you try with Firefox 48 (current Nightly)? I think the strict_min_version might be wrong for this one...

**Comment by ind4rk** [comment]
on Firefox Nightly x64 version 48.0a1 (2016-04-25) works. OS linux ubuntu. :)

**Comment by wbamberg** [comment]
I've just pushed https://github.com/mdn/webextensions-examples/commit/b75b18226208a09a0a29aa51f83319d19c1f8e18, which should fix strict_min_version for this example.

Thanks for finding this! I'll close this for now, but let me know if you think anything else is needed.

**Comment by ind4rk** [comment]
Is offtopic but in webextensions-examples-> README.md 
"Before you try out these extensions, read about prerequisites."
if you click on the link. 
"All you need is Firefox 45 or higher. See Your first WebExtension to get started."
is my fault for not check the manifest.json but this  line  confus me.
sorry for my english :P

**Comment by wbamberg** [comment]
You're right, that's super-confusing. I just updated the README:

https://github.com/mdn/webextensions-examples/blob/master/README.md

Is this better, do you think?
