### ISSUE TITLE
minor bug with native messaging example

### ISSUE THREAD

**Issue by dahn-zk** [mdn/webextensions-examples#557]
this line will throw when you create required key in `HKEY_LOCAL_MACHINE` instead of `HKEY_CURRENT_USER` ( which is allowed ) , so this script should not behave like this :
https://github.com/mdn/webextensions-examples/blob/faadfca8ddce0c02cc20c3c261c76a9b50073122/native-messaging/check_config_win.py#L22

also , as the script is in Python anyway , the whole thing can be simplified using for-else :

```
for root in key_roots:
    try:
        key = winreg.OpenKey(getattr(winreg, root), key_path)
        print('Checking:', root, key_path)
        res = winreg.QueryValueEx(key, '')
    except FileNotFoundError:
        continue
    break
else:
    raise ValueError('Could not find a registry entry, aborting.')
```

let me know if you want me rather create a small PR with this fix

**Comment by Rob--W** [comment]
Thanks for the report. Please submit a PR and I will merge it.
