### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by transfluxus** [mdn/webextensions-examples#58]
I have a general question, 
I have problems understanding end getting these add-ons to run.
I wanted to have a look at favorite color. 
The docs talk about a manifest.json but from jpm this is actually called package.json.
so renamed the file but it was missing a name, a title, the format of the version was incorrect and I had to add an index.js.
When I could run it with jpm, the new browser window didn't had any browser action button, probably cuz the the json file lacks information about the icon.
Can somebody tell me why so many things are off?

**Comment by wbamberg** [comment]
These add-ons are not Add-on SDK add-ons, they are WebExtensions.

WebExtensions don't have package.json and don't run with jpm.

The add-ons in this repo should install and run without any modifications. Try following the instructions here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Packaging_and_installation to install them.
