### ISSUE TITLE
inpage-toolbar-ui -> ui.js file

### ISSUE THREAD

**Issue by alihassangoraya** [mdn/webextensions-examples#59]
It always show in console that chrome is not defined. I am unable to connect to background page from the page/content loaded in iframe.

**Comment by wbamberg** [comment]
This add-on works fine for me: https://i.imgur.com/QiP0qFm.gif
This is Firefox 48.0a2, the current Developer Edition. Which Firefox are you using, please?

It does seem to work only on an actual web content page (it doesn't work in special pages like about:addons or about:debugging).

**Comment by alihassangoraya** [comment]
Hi, I had firefox version 45.0, and it was showing error in console "chrome is not defined" Now I have updated the firefox to 46.0.1 and now it is working.

I was trying on actual pages already.

Now my question is that which versions of firefox are supported for this addon?

Thanks in advance. :)

**Comment by wbamberg** [comment]
I'm glad it worked for you :).

> Now my question is that which versions of firefox are supported for this addon?

It should work from Firefox 46 onwards.

In general, I'd suggest you use Firefox Developer Edition (currently Firefox 48) if you can.

To know which Firefox version a particular example needs, you can check the value of strict_min_version in the manifest.json: https://github.com/mdn/webextensions-examples/blob/master/inpage-toolbar-ui/manifest.json#L37.

There's also this page: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs which should give you an idea of which Firefox versions particular APIs landed in (but note that this doesn't always give you the answer - for example, runtime.connect() was present in Fx45, but was not available in content until Firefox 46).

Hope that helps.

**Comment by alihassangoraya** [comment]
many many thanks for your response. :) Its really helpful.
