### ISSUE TITLE
favourite-colour extension and openOptionsPage don't work

### ISSUE THREAD

**Issue by andriussev** [mdn/webextensions-examples#64]
The mentioned extension relies on runtime's `openOptionsPage()` which does not seem to work.

Clicking on the toolbar button returns this to the browser console:
`chrome.runtime.openOptionsPage is not a function background.js:2:0`

Is it a global problem with `openOptionsPage()` or is the extension doing something incorrectly?

**Comment by wbamberg** [comment]
Which version of Firefox are you using? runtime.openOptionsPage() is only supported from Firefox 48 onwards (the current Developer Edition): https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Runtime/openOptionsPage#Browser_compatibility

**Comment by andriussev** [comment]
Thank you for the response.
Apparently, this somehow slipped through my eyes as I was using the standard Firefox.
I guess, I'll have to skip this functionality until it's closer to being ready for all FF users.
