### ISSUE TITLE
NotFoundError when executing context-menu-demo

### ISSUE THREAD

**Issue by moekraft** [mdn/webextensions-examples#69]
I am testing the context-menu-demo on Firefox 45.2 ESR. I am hitting a Node NotFoundError in ext-contextMenu.js in the handleEvent after selecting a menu item in the demo context menu. 
![context-menu](https://cloud.githubusercontent.com/assets/12103268/16133943/8ad8788e-33e8-11e6-8d78-cc5a052ed768.png)

handleEvent: function(event) {
    let target = event.target;

    target.removeEventListener("popuphidden", this);
    for (let item of this._itemsToCleanUp) { 
      target.removeChild(item); **<=hitting NotFoundError here**
    }
    // Let's detach the top level items.
    this._itemsToCleanUp.clear();
  },

  _itemsToCleanUp: new Set(),
};

**Details:**
![nodenotfounderror](https://cloud.githubusercontent.com/assets/12103268/16133951/95bf1eec-33e8-11e6-8354-ae724e1dbd21.png)

**Comment by wbamberg** [comment]
I haven't tested with the ESR, but yes, it looks like this API does not work before Firefox 48 (the current Beta). Is it important to you to use Firefox 45 ESR? I think in general WebExtensions won't work very well in Firefox 45, as that's a very early version.

The first "stable release" of WebExtensions is coming in Firefox 48, and the example does work there. I'll update the "strict_min_version" key to Firefox 48, as a hint about that, and see if we should update the compatibility data as well.

**Comment by wbamberg** [comment]
Yes, I see exactly what you are seeing with the ESR.

**Comment by moekraft** [comment]
Thanks much. I'll give FF 48 a try. - Moe

**Comment by wbamberg** [comment]
I've updated "strict_min_version" for the contextMenus example, so am closing this bug.
