### ISSUE TITLE
Remove id from the examples

### ISSUE THREAD

**Issue by andymckay** [mdn/webextensions-examples#71]
Given that we expect the examples to be copied and re-used, we should probably remove the applications section, or at least the id from all the add-ons. That way developers can copy them and get them signed on AMO and check out the whole process without having to get into ID collisions.

Maybe wait till web-ext lands with no id support: mozilla/web-ext#178

**Comment by wbamberg** [comment]
@andymckay - do you think we should keep the strict_min_version (and by implication the applications key)?

(I think probably we should, because people get into enough difficulties with versions as it is. The downside of course is that it provokes warnings in Chrome.)

**Comment by andymckay** [comment]
Good point, we should. Agreed.

**Comment by kumar303** [comment]
If you leave in the strict_min_version, beware the AMO will refuse to sign it without an ID when you require a Firefox less than 47:

    Server response: GUID is required for Firefox 47 and below.

**Comment by wbamberg** [comment]
@kumar303 : is that <47, or <=47?

Your comment suggests <, but your quote suggests <=.

If 47 is OK, then I'd probably suggest updating strict_min_version to 47 for every example (except those that need 48 or 49 of course). But if 47 is not OK, it's a bit tricker, because 47 is the current release Firefox.

**Comment by kumar303** [comment]
Hmm. Yes, the error message makes it seem like <= 47 but I haven't tried uploading to AMO to verify.

**Comment by kumar303** [comment]
Scratch that. I tested it on AMO. To upload an extension without an ID *and* a `strict_min_version` you have to set `strict_min_version = 48`

**Comment by wbamberg** [comment]
To summarise, options are:

**1) remove "applications" entirely.**

Pros:
* add-ons will get automatic IDs, so no ID collisions if people copy these add-ons and submit them to AMO.
* add-ons will install in Chrome with no warnings.

Cons:
* there will be no "strict_min_version", so people won't get a clue when they install, say, favourite-colour on Firefox 47. We could document version requirements more obviously, to try to help with that.

**2) remove "applications/id", but keep "applications/strict_min_version" the same**

Pros:
* add-ons will get automatic IDs, so no ID collisions if people copy these add-ons and submit them to AMO.
* users will get a clue about version compatibility (via "applications/strict_min_version")

Cons:
* if "applications/strict_min_version" is <48, then AMO will give an error.

**3) remove "applications/id", keep "applications/strict_min_version", and set it to Firefox 48 or higher**

Pros:
* add-ons will get automatic IDs, so no ID collisions if people copy these add-ons and submit them to AMO.
* users will get a clue about version compatibility (via "applications/strict_min_version")

Cons:
* add-ons will not install in Firefoxes 47 and below

**4) change nothing: keep "applications/id", and "applications/strict_min_version"**

Pros:
* add-ons will install in release Firefox
* users will get a clue about version compatibility (via "applications/strict_min_version")
* users will be able to submit add-ons to AMO

Cons:
* add-ons will get ID collisions if users submit them to AMO without changing the ID

I think:
* while Firefox 47 is the release Firefox, (3) is a non-starter. 
* (2) will give people quite obscure errors if they try to submit to AMO
* given that people are already often confused about version compatibility, I'm not happy with (1).
...meaning we are stuck with (4) until after Firefox 48 ships. Then we could do (3).

**Comment by andymckay** [comment]
3) sounds good to me. Firefox 48 is so close now, may as well just wait for
that.

**Comment by kumar303** [comment]
Could we re-evaluate option 1, to remove applications entirely? The release build of Firefox is now at version 49 so it seems reasonable to me.

If some example in the future needs to rely on an API in a newer Firefox, we could make the manifest look like option 3: remove "applications/id", keep "applications/strict_min_version", and set it to Firefox NNN or higher

**Comment by andymckay** [comment]
Agreed. If the `strict_min_version` is less than the release version of Firefox, I would agree with removing `applications` completely.

**Comment by wbamberg** [comment]
As far as I know there are 2 cases where you need `applications.gecko.id`:
* if you want to have an options page
* if you want to use native messaging (this one is not an absolute requirement, but you do need an ID to set in the app manifest, and setting applications.gecko.id is the sanest way to do this.

So I guess any examples that meet these criteria should keep `applications.gecko.id`. I think, at the moment, this is only:
https://github.com/mdn/webextensions-examples/tree/master/favourite-colour
https://github.com/mdn/webextensions-examples/tree/master/native-messaging

Also, as Andy says, some examples have a strict_min_version >= the Firefox release version, and I'd suggest we keep `applications.gecko.strict_min_version` for these examples.

Does that cover it?

**Comment by andymckay** [comment]
The options page bug got fixed in Firefox 49,
https://bugzilla.mozilla.org/show_bug.cgi?id=1293721

I think its just nativeMessaging that's left.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/144.
