### ISSUE TITLE
Youtube video selects borderify.js but mozilla webpage text says select manifest.json

### ISSUE THREAD

**Issue by SRGOM** [mdn/webextensions-examples#75]
Btw, you should probably publish a direct link on each page to where community can go ahead and fix minor bugs like this.

**Comment by wbamberg** [comment]
Thanks for this! I've updated the page: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension.

> Btw, you should probably publish a direct link on each page
> to where community can go ahead and fix minor bugs like this.

All MDN pages have a link called "Edit", which, if you click it, will ask you to sign in (if you are not signed in already) then open the page in an editor.

Do you mean that each MDN page should include a link labeled "Fix this page" or something, that would do the same thing as "Edit"?

**Comment by SRGOM** [comment]
I see the very very clear "EDIT" button now. Sorry I think I was looking at the bottom for some (wrong) reason...
