### ISSUE TITLE
beastify.js

### ISSUE THREAD

**Issue by oxidian24** [mdn/webextensions-examples#77]
I see a gap in some examples like Beastify. I see it should be simple as possible, but the problem is that you did not make it clear enough that HTML page or HTML document must be loaded (or I did not realized it). It took few days to me to realize that when I open new Tab in Firefox, it is not html page (**it looks like html doc but is not**). As far as I understand the problem - the Window exists but the document was not created. So when I tried your addon nothing displayed in the Window.

The function

`function insertBeast(beastURL) {
  var beastImage = document.createElement("img");
  beastImage.setAttribute("src", beastURL);
  beastImage.setAttribute("style", "width: 100vw");
  beastImage.setAttribute("style", "height: 100vh");
  document.body.appendChild(beastImage);
}
`
Can not create any document, because you did not check if the document exists and did not create the document in the case that the document does not exists (but window does). Please add the fix.

Also a back-reference to the second tutorial would be helpful. Also add a link to first tutorial to borderify.js . Because I did come here from different link and I did not see the explanation which is there. Now, I do not know the links which are to the rest of the examples, if there are some tutorials which I should see related to them.

**Comment by anaran** [comment]
Have you seen
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples
yet?

There are also homepage links in about:addons in your browser.

Which browser version on which OS are you using?

Also, when describing a problem it is always helpful to answer these questions, for other to get proper context:

- What did you do? (steps to reproduce)
- What happened? (actual results)
- What should have happened? (expected results)

> It took few days to me to realize that when I open new Tab in Firefox, it is not html page

If I understand this correctly then you did the equvalent of

New Tab 	Ctrl + T

The toolbar icon appears, the menu appears when you click it, but no beast is loaded, right?

The browser console says something similar to
> Unchecked lastError value: Error: No matching window
right?

**Comment by oxidian24** [comment]
I use FF 48 beta.
No, I did not see it, now for first time.
I was on empty page (e.g. Ctrl+Tab) or on about:debugging#addons. The previous looks like normal webpage because there is search bar and some links to my visited sites. Now I relelize the page contains DOM, so there must be document. I don't know why the beastify cannot work as expected here. I need to go to e.g. google.com .... and then I click on the footprint icon. So it works when there is html page loaded. No on the "empty" page or "about:debugging" page.

_"The toolbar icon appears, the menu appears when you click it, but no beast is loaded, right?"_
Exactly. Nothing happens when I click on the item on the popup. I can click as many times as I want.
No change in browser window (is this is what you mean by console).

I found one more _bug_ when I am working with popup (similar to Beastify). I can add it here later.

**Comment by wbamberg** [comment]
> So it works when there is html page loaded. No on the "empty" page or "about:debugging" page.

Yes, it seems like tabs.executeScript doesn't work for about: pages (the empty page is an about: page as well - about:newtab) - that's where the "No matching window" error comes from.

I can see how this would be confusing to a lot of people. I'm not sure what the best solution is though. The only thing I can think of is to catch the error and log something more understandable, like "Can't beastify this page - try using a normal HTTP(S) page". And update the README to be more explicit about this.

> "The toolbar icon appears, the menu appears when you click it, but no beast is loaded, right?"
> Exactly. Nothing happens when I click on the item on the popup. I can click as many times as I want.
> No change in browser window (is this is what you mean by console). 

No, the console is a debugging tool that displays error messages and messages logged by the add-on: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Viewing_log_output.

**Comment by oxidian24** [comment]
Anaran used term "Browser console" not Addons Debugger Console. That's why my reaction was in that way. I know what is Addons Debugger Console. But I don't know what is browser console. That's that. There is also Developers tool Console. Which does not work for addons.

May I add here some another information related to popup "strange behaviour"? I created a project from Beastify. Instead Frog, Snake and Turtle I used 4 icons with decription. First time when I click a button, popup appears with 4 items. Everything looks nice. But sometimes it seems that it does not react, so I click and nothing happens. Nexttime I click and I must wait - I guess some 200-300ms delay to open a single popup with 4 divs and 4 images... Next time I click and new set of icons is set to the same popup. So now there are 8 icons instead 4. Next time I click and nothing happens. Next time I click and I must wait about 900-1200ms to appear the popup but this time 12 icons there..  And so on. Then after hours - just now - I am clicking many times and no popup appears (just arrow up). I wait few seconds and click again and it appears 4 icons (but ). Click again, nothing. Click again 4 icons. So I could upload my extension if I find suitable location and you could check it if it does the same thing for you. Maybe there is some bug in the Addons API. I think it should work but doesn't.

**Comment by wbamberg** [comment]
> So I could upload my extension if I find suitable location and you could check it if it does the same thing for you. Maybe there is some bug in the Addons API. I think it should work but doesn't.

Yes, please do.

**Comment by oxidian24** [comment]
I would do but I cannot find how to create directory. Should I upload zip file? I tried to upload files here to my first Repository but it did not uploaded directories.

**Comment by wbamberg** [comment]
Yes, you could upload a zip of the entire add-on.

**Comment by oxidian24** [comment]
Sorry. I did not manage to upload the file. My [issue](https://github.com/oxidian24/popup-test/issues/1)

**Comment by oxidian24** [comment]
I uploaded the zip file, but I am not sure if it is really there because I don't see it.

**Comment by wbamberg** [comment]
Try emailing it to me at my username dot mozilla dot com :).

**Comment by oxidian24** [comment]
OK, I sent you email with attachment. The Repository upload still did not finished is some problem with it.

**Comment by oxidian24** [comment]
I think there should be more explanation about the Beastify addon. Esspecially about activeTab permission. I mean help people to find relations between the things which are there but are not obvious untill you read the docs completely. I think you could add the text as a comment before the line where Content Script is executed:

# activeTab permission

This permission is specified as "activeTab". If an extension has the activeTab permission, then when the user interacts with the extension (for example: clicks its browser action or page action, or selects its context menu item), the extension is granted extra privileges for the active tab only.

The extra privileges are:

- the ability to inject JavaScript or CSS into the tab programmatically, using chrome.tabs.executeScript and chrome.tabs.insertCSS
- access to the privileged parts of the tabs API for the current tab: Tab.url, Tab.title, and Tab.faviconUrl.

Also, I would like to see some example how to open new tab from the popup. It is definitevly not clear how to do it when you don't have permission and when a single browser action "options_ui" is not enough. I have a list of icons and want to open tabs when I click a icon, just like in Favourite color example but in non-addons tab. But that example is fixed only with a button and the Beastify popup does not open any tab, just executes a script in current tab. So where can I learn it when it is not there?

**Comment by oxidian24** [comment]
When I am sending a message
```
browser.tabs.sendMessage(
  tabId,                   // integer
  message,                 // any
  options,                 // optional object
  function(response) {...} // optional function
)

```
How can I find tabId? In examples you use tab[0]. But when I open page, I don't know what is the tab's id. I wish not to open new page every time when I click on the same item in popup. So when I open "Advanced settings" and click again, there should not be opened new tab with advanced setting form because it is already opened. I can imagine sending a message to ask the ID which I need in main script which opened new tab. But here is the part which is not clear to me. I do not know the tabId so what should I use. Is it valid to use null instead tab[n]? What will happen? I expect that if tab[n] present, it sends message to particular window, right? Are the messages kept separated for every window or are they in one container? If they are in one container, then why should I could not to use null? All windows which have listener needs to check message container, don't they? So would be something wrong if I would send message to all tabs and only the window which url is equal to the url in the parameter options.url will respond to the message.

**The reason why I want to do this messaging is because need to know the Id of th new tab which was created to prevent the same tab to be opened several times in separated tabs.**

**Comment by wbamberg** [comment]
tabs.create takes a callback parameter, that's called with the new tab's ID. Please check the documentation: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Tabs/create.

This issue tracker is for bugs in the examples repo, not for general support with WebExtensions. If you need general support, please try:
https://discourse.mozilla-community.org/c/add-ons
or
https://mail.mozilla.org/listinfo/dev-addons
