### ISSUE TITLE
beastify: double entry of beastNameToURL

### ISSUE THREAD

**Issue by silvio** [mdn/webextensions-examples#78]
In [/beastify/content_scripts/beastify.js] and [/beastify/popup/choose_beast.js] exists two time the `beastNameToURL` function.

[/beastify/content_scripts/beastify.js]: https://github.com/mdn/webextensions-examples/blob/83bdefd6a4c6800e1d6e03459f306b2c64658446/beastify/content_scripts/beastify.js
[/beastify/popup/choose_beast.js]: https://github.com/mdn/webextensions-examples/blob/83bdefd6a4c6800e1d6e03459f306b2c64658446/beastify/popup/choose_beast.js

**Comment by wbamberg** [comment]
Thanks for filing!
-> https://github.com/mdn/webextensions-examples/commit/ec1830914e2ee2cc1dd9ac431574fcb5d2735659
