### ISSUE TITLE
Ubuntu 16, Firefox 47

### ISSUE THREAD

**Issue by tgkprog** [mdn/webextensions-examples#80]
API like : 

    chrome.browserAction.onClicked.addListener(send1);

Don't work on firefox 47 on Ubuntu 16.0.4 LTS . Could you mention that? Wasted a lot of time trying to make things work. Finally put it around a try catch to see "chrome.browserAction is undefined"

**Comment by aswan** [comment]
@tgkprog: there's an inconsistency above, your exception says: `"hrome.browserAction is undefined"`, but of course you want `chrome.browserAction` or `browser.browserAction`.
If that's just a copy/paste error, can you include a link to the full code for your extension?

**Comment by tgkprog** [comment]
This is issue is there on Ubuntu 16, Firefox 47, Yes I changed the code. My code is at https://github.com/tgkprog/webExtnNotifyUrlWS/blob/891cc6ef25094842d5b9156b174cb6cbed1f2424/code/notify.js#L88

**Comment by rpl** [comment]
I just tried to load the extension linked above on my system:

- lsb_release: Ubuntu 16.04.1 LTS
- Firefox version: 47.0 (installed from apt, built from Canonical)

Once the extension is started, its browserAction button is visible in the toolbar, and when I click on the browserAction button I get the following logs in the Browser Console:

```
send1 request1                                                                                        | notify.js:13:2
An error occurred while transferring the file.[object ProgressEvent]       | notify.js:71:3
e hist add 1                                                                                              | notify.js:165:2
e hist add end                                                                                          | notify.js:181:2
```

which, at least from a brief look at the sources, seems to confirm that the browserAction onClicked listener has been called. 

To be even more sure that the listener is called everytime the button has been clicked, I also tried to set a breakpoint from the Browser Toolbox and I've been able to step through the send1 function, and so the onClicked listener seems to work without issues on my system.

Have you already tried to reproduce the issue on a clean profile (e.g. a newly created profile without any other addon installed)?

**Comment by tgkprog** [comment]
Hmm its working now. Maybe my permissions were not right earlier. I dunno. Sorry. but I read somewhere on the mozilla site that this feature is in 48 and beyond so was testing on 48 on my windows... and beta on ubuntu. anyway closing this. thank you for your time.
