### ISSUE TITLE
Multiple installation, multiple same context menu and ... weird bug with the webextension api

### ISSUE THREAD

**Issue by Nomia** [mdn/webextensions-examples#81]
Hi,

Two problems,
1.try install your context-menu-demo extension, try to uninstall it and install it multiple times, then you can see there are multiple same contextmenus
2.I developed a extension last week, it works fine, and changed nothing after a week, things goes wrong, I can see an error in the browser console, it says "Port error: Could not establish connection. Receiving end does not exist". i googled around, and tried every solution(api version, backgroundjs->backgroundpage,etc) suggested, error still appear in the console. Then i try to install your demo extensions. each of them throw an error "chrome is not defined". But after 12 hours, i tried again. all of them and my extension worked again. However, after 3 hours by then, error throwed again.

firefox 48

I think it's the internal bugs, please let me know if there is any fix to this problem, 

Thanks.

**Comment by wbamberg** [comment]
The first issue is a known bug: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1246044 (I don't know why it has this confusing title).

For the second, could you please file a bug against WebExtensions? https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&Component=WebExtensions
