### ISSUE TITLE
ui.js ReferenceError

### ISSUE THREAD

**Issue by freetomas** [mdn/webextensions-examples#82]
When ui.js runs it throws a reference error:"chrome is not defined" on 

> var port = chrome.runtime.connect();

Looks like ui.js runs in the context of the page loosing the access to web extension API.
Anyone knows why this happen? I'm really interested in this feature

Tested on Firefox ESR 45.2.0 ( that does support chrome.runtime.connect() )
Debugged with Browser Toolbox

**Comment by rpl** [comment]
The usage of the WebExtension APIs from injected iframes with a "moz-extension" url (if listed in the `web_accessible resources`) are only supported starting from Firefox >= 46.

(`strict_min_version` in the manifest.json of the examples is set to the initial supported version, if the APIs used are supported only starting from a defined Firefox release, eg. https://github.com/mdn/webextensions-examples/blob/master/inpage-toolbar-ui/manifest.json#L37)

**Comment by andymckay** [comment]
Closing based on the last comment.
