### ISSUE TITLE
How can I apply cookie inside popup?

### ISSUE THREAD

**Issue by gladisihor** [mdn/webextensions-examples#91]
How can I apply cookie inside popup? For example when I entered color code into input and closed popup I expected that color was stay here in input. But input stay empty. One more example: I want to toggle active class by click on buttons so I could change border color for them and save it after closing and opening popup. Say please how can I use cookies for such cases?

**Comment by wbamberg** [comment]
The popup's document is reloaded each time it is opened, so it loses any state it had.

If you want to save data permanently (i.e. across Firefox restarts) use the [storage API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage). The [favourite-colour add-on](https://github.com/mdn/webextensions-examples/tree/master/favourite-colour) gives you an example of this.

If you only need to save state across popup-openings, you could perhaps set the state in the background page using [runtime.getBackgroundPage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getBackgroundPage), doing something like this:

```
chrome.runtime.getBackgroundPage((page) => {
  if (page.popupContent) {
    document.querySelector("#content").value = page.popupContent;
  }
});

function setState() {
  console.log(document.querySelector("#content").value);
  chrome.runtime.getBackgroundPage((page) => {
    page.popupContent = document.querySelector("#content").value;
  });
}

document.querySelector("#content").addEventListener("keyup", setState, false);
```

Note that you do need to have included a background page in your add-on for this to work. Also I'm not sure whether listening to keyup is the best idea, but it does seem to work.

**Comment by gladisihor** [comment]
Thank you a lot! Your code works!!!
