### ISSUE TITLE
WebExtension example favourite-colour throws error

### ISSUE THREAD

**Issue by Solaner** [mdn/webextensions-examples#95]
The WebExtension example [favourite-colour](https://github.com/mdn/webextensions-examples/tree/master/favourite-colour) appears to be working well, but always when I press the Save button it throws an exception which can be seen in the Console of the Developer Toolbar:
TypeError: this._recipeManager is null [Learn More] LoginManagerParent.jsm:77:9.
As the functionality does not seem to be affected, I woult rate it as a low priority fault.

**Comment by kartik95** [comment]
What does this extension do exactly? Because whenever I try to use this extension, it redirects me to the extensions page. @wbamberg @andymckay

**Comment by andymckay** [comment]
Demonstrates an options_ui page and saving a value in chrome.storage.local.

**Comment by kartik95** [comment]
Okay. But what is the use of this extension? @andymckay

**Comment by andymckay** [comment]
To demonstrate the above points. This repository full of examples showing developers how to use the APIs for their own extensions.

**Comment by kartik95** [comment]
Okay thanks! I'll start with it then. :)

**Comment by andymckay** [comment]
I think you might find that this message comes from Firefox and has nothing to do with the code in this repository. So just a warning, you might find yourself off over in that codebase.

**Comment by kartik95** [comment]
Oh, okay. So why is this issue still opened? (Just curious)

**Comment by andymckay** [comment]
Because no-one has looked at it until you did 19 minutes ago :)

**Comment by kartik95** [comment]
Haha, okay. Well, glad to hear that. :)
