### ISSUE TITLE
How to create a notification with custom button?

### ISSUE THREAD

**Issue by julindra** [mdn/webextensions-examples#98]
I'm following this guide -> https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Notifications/create

I've try something like this, but the buttons always throwing an error. Anyone can help me? Thanks

````
var opt = {
	type: "basic",
	title: "title",
	message: "msg",
	buttons: [{
		title: "Copy",
	}, {
		title: "Close",
	}],
	iconUrl: "image.png"
}
chrome.notifications.create("some_id", opt);
````

**Comment by wbamberg** [comment]
Buttons aren't supported in Firefox. See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions.

**Comment by julindra** [comment]
Ah ok. Thanks!

**Comment by wbamberg** [comment]
There's a bug filed for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1190681 - looks like it has some attention, but isn't going to be fixed very soon.
